package com.omgimalexis.allthethings.init;

import com.omgimalexis.allthethings.utility.LogHelper;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.material.Material;
import net.minecraftforge.fluids.Fluid;
import net.minecraftforge.fluids.FluidRegistry;

public class ModFluids {
	public static final Fluid moltenIronFluid = new Fluid("moltenIron").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenGoldFluid = new Fluid("moltenGold").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenCopperFluid = new Fluid("moltenCopper").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenTinFluid = new Fluid("moltenTin").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenLeadFluid = new Fluid("moltenLead").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenSilverFluid = new Fluid("moltenSilver").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenBronzeFluid = new Fluid("moltenBronze").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenPlatinumFluid = new Fluid("moltenPlatinum").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenZincFluid = new Fluid("moltenZinc").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenSolderFluid = new Fluid("moltenSolder").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenBrassFluid = new Fluid("moltenBrass").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenElectrumFluid = new Fluid("moltenElectrum").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenMalagniteFluid = new Fluid("moltenMalagnite").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenAluminiumFluid = new Fluid("moltenAluminium").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenGoloidFluid = new Fluid("moltenGoloid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenSiliconFluid = new Fluid("moltenSilicon").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenVoidiumFluid = new Fluid("moltenVoidium").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenRhodiumFluid = new Fluid("moltenRhodium").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenTungstenFluid = new Fluid("moltenTungsten").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenCobaltFluid = new Fluid("moltenCobalt").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenInvarFluid = new Fluid("moltenInvar").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenTrytementiumFluid = new Fluid("moltenTrytementium").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenNickelFluid = new Fluid("moltenNickel").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenChromiumFluid = new Fluid("moltenChromium").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenUnobtaniumFluid = new Fluid("moltenUnobtanium").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenPlutoniumFluid = new Fluid("moltenPlutonium").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenUraniumFluid = new Fluid("moltenUranium").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenIridiumFluid = new Fluid("moltenIridium").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenBluriteFluid = new Fluid("moltenBlurite").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenRuniteFluid = new Fluid("moltenRunite").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenRubiumFluid = new Fluid("moltenRubium").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenLunarFluid = new Fluid("moltenLunar").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenOpalFluid = new Fluid("moltenOpal").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenDaeyaltFluid = new Fluid("moltenDaeyalt").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenRubyFluid = new Fluid("moltenRuby").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenSapphireFluid = new Fluid("moltenSapphire").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenEmeraldFluid = new Fluid("moltenEmerald").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenDiamondFluid = new Fluid("moltenDiamond").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenNetherQuartzFluid = new Fluid("moltenNetherQuartz").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenObsidianFluid = new Fluid("moltenObsidian").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenOnyxFluid = new Fluid("moltenOnyx").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenKunziteFluid = new Fluid("moltenKunzite").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenAmberFluid = new Fluid("moltenAmber").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenGarnetFluid = new Fluid("moltenGarnet").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenAmazoniteFluid = new Fluid("moltenAmazonite").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenFyrestoneFluid = new Fluid("moltenFyrestone").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenAquamarineFluid = new Fluid("moltenAquamarine").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenTopazFluid = new Fluid("moltenTopaz").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenCarnelianFluid = new Fluid("moltenCarnelian").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenJadeFluid = new Fluid("moltenJade").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenAmethystFluid = new Fluid("moltenAmethyst").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenCitrineFluid = new Fluid("moltenCitrine").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenMithrilFluid = new Fluid("moltenMithril").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static final Fluid moltenManganeseFluid = new Fluid("moltenManganese").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	
	public static void init() {
		FluidRegistry.registerFluid(moltenIronFluid);
		FluidRegistry.registerFluid(moltenGoldFluid);
		FluidRegistry.registerFluid(moltenCopperFluid);
		FluidRegistry.registerFluid(moltenTinFluid);
		FluidRegistry.registerFluid(moltenLeadFluid);
		FluidRegistry.registerFluid(moltenSilverFluid);
		FluidRegistry.registerFluid(moltenBronzeFluid);
		FluidRegistry.registerFluid(moltenPlatinumFluid);
		FluidRegistry.registerFluid(moltenZincFluid);
		FluidRegistry.registerFluid(moltenSolderFluid);
		FluidRegistry.registerFluid(moltenBrassFluid);
		FluidRegistry.registerFluid(moltenElectrumFluid);
		FluidRegistry.registerFluid(moltenMalagniteFluid);
		FluidRegistry.registerFluid(moltenAluminiumFluid);
		FluidRegistry.registerFluid(moltenGoloidFluid);
		FluidRegistry.registerFluid(moltenSiliconFluid);
		FluidRegistry.registerFluid(moltenVoidiumFluid);
		FluidRegistry.registerFluid(moltenRhodiumFluid);
		FluidRegistry.registerFluid(moltenTungstenFluid);
		FluidRegistry.registerFluid(moltenCobaltFluid);
		FluidRegistry.registerFluid(moltenInvarFluid);
		FluidRegistry.registerFluid(moltenTrytementiumFluid);
		FluidRegistry.registerFluid(moltenNickelFluid);
		FluidRegistry.registerFluid(moltenChromiumFluid);
		FluidRegistry.registerFluid(moltenUnobtaniumFluid);
		FluidRegistry.registerFluid(moltenPlutoniumFluid);
		FluidRegistry.registerFluid(moltenUraniumFluid);
		FluidRegistry.registerFluid(moltenIridiumFluid);
		FluidRegistry.registerFluid(moltenBluriteFluid);
		FluidRegistry.registerFluid(moltenRuniteFluid);
		FluidRegistry.registerFluid(moltenRubiumFluid);
		FluidRegistry.registerFluid(moltenLunarFluid);
		FluidRegistry.registerFluid(moltenOpalFluid);
		FluidRegistry.registerFluid(moltenDaeyaltFluid);
		FluidRegistry.registerFluid(moltenRubyFluid);
		FluidRegistry.registerFluid(moltenSapphireFluid);
		FluidRegistry.registerFluid(moltenEmeraldFluid);
		FluidRegistry.registerFluid(moltenDiamondFluid);
		FluidRegistry.registerFluid(moltenNetherQuartzFluid);
		FluidRegistry.registerFluid(moltenObsidianFluid);
		FluidRegistry.registerFluid(moltenOnyxFluid);
		FluidRegistry.registerFluid(moltenKunziteFluid);
		FluidRegistry.registerFluid(moltenAmberFluid);
		FluidRegistry.registerFluid(moltenGarnetFluid);
		FluidRegistry.registerFluid(moltenAmazoniteFluid);
		FluidRegistry.registerFluid(moltenFyrestoneFluid);
		FluidRegistry.registerFluid(moltenAquamarineFluid);
		FluidRegistry.registerFluid(moltenTopazFluid);
		FluidRegistry.registerFluid(moltenCarnelianFluid);
		FluidRegistry.registerFluid(moltenJadeFluid);
		FluidRegistry.registerFluid(moltenAmethystFluid);
		FluidRegistry.registerFluid(moltenCitrineFluid);
		FluidRegistry.registerFluid(moltenMithrilFluid);
		FluidRegistry.registerFluid(moltenManganeseFluid);
		
		LogHelper.info("Fluids initialized successfully!");
	}
}
