package com.omgimalexis.allthethings.init;

import com.omgimalexis.allthethings.utility.LogHelper;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.oredict.ShapedOreRecipe;
import cpw.mods.fml.common.registry.GameRegistry;

public class ModRecipes {

	public static void init() {
		// Gems to blocks
		GameRegistry.addRecipe(new ShapedOreRecipe(ModBlocks.blockAmber, true, new Object[]{"xxx", "xxx", "xxx", Character.valueOf('x'), "gemAmber"}));
		GameRegistry.addRecipe(new ShapedOreRecipe(ModBlocks.blockRuby, true, new Object[]{"xxx", "xxx", "xxx", Character.valueOf('x'), "gemRuby"}));
		GameRegistry.addRecipe(new ShapedOreRecipe(ModBlocks.blockSapphire, true, new Object[]{"xxx", "xxx", "xxx", Character.valueOf('x'), "gemSapphire"}));
		GameRegistry.addRecipe(new ShapedOreRecipe(ModBlocks.blockOnyx, true, new Object[]{"xxx", "xxx", "xxx", Character.valueOf('x'), "gemOnyx"}));
		GameRegistry.addRecipe(new ShapedOreRecipe(ModBlocks.blockCitrine, true, new Object[]{"xxx", "xxx", "xxx", Character.valueOf('x'), "gemCitrine"}));
		GameRegistry.addRecipe(new ShapedOreRecipe(ModBlocks.blockJade, true, new Object[]{"xxx", "xxx", "xxx", Character.valueOf('x'), "gemJade"}));
		GameRegistry.addRecipe(new ShapedOreRecipe(ModBlocks.blockAmethyst, true, new Object[]{"xxx", "xxx", "xxx", Character.valueOf('x'), "gemAmethyst"}));
		GameRegistry.addRecipe(new ShapedOreRecipe(ModBlocks.blockCarnelian, true, new Object[]{"xxx", "xxx", "xxx", Character.valueOf('x'), "gemCarnelian"}));
		GameRegistry.addRecipe(new ShapedOreRecipe(ModBlocks.blockVoidium, true, new Object[]{"xxx", "xxx", "xxx", Character.valueOf('x'), "gemVoidium"}));
		GameRegistry.addRecipe(new ShapedOreRecipe(ModBlocks.blockFyrestone, true, new Object[]{"xxx", "xxx", "xxx", Character.valueOf('x'), "gemFyrestone"}));
		// Blocks back to gems
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.gemAmber, 9), ModBlocks.blockAmber);
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.gemRuby, 9), ModBlocks.blockRuby);
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.gemSapphire, 9), ModBlocks.blockSapphire);
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.gemOnyx, 9), ModBlocks.blockOnyx);
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.gemCitrine, 9), ModBlocks.blockCitrine);
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.gemJade, 9), ModBlocks.blockJade);
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.gemAmethyst, 9), ModBlocks.blockAmethyst);
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.gemCarnelian, 9), ModBlocks.blockCarnelian);
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.voidium, 9), ModBlocks.blockVoidium);
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.fyrestone, 9), ModBlocks.blockFyrestone);
		// Fossilized Resin to Amber
		GameRegistry.addRecipe(new ItemStack(ModItems.gemAmber), " r ", "rrr", " r ", 'r', ModItems.fossilResin);
		// Rings and Bands
		GameRegistry.addRecipe(new ItemStack(ModItems.goldBand,9), "ggg", 'g', Items.gold_ingot);
		GameRegistry.addRecipe(new ItemStack(ModItems.silverBand,9), "ggg", 'g', ModItems.ingotSilver);
		// Tools (& Swords, but I count them as tools anyway...)
		GameRegistry.addRecipe(new ItemStack(ModTools.onyxPickaxe), "ooo", " s", " s", 'o', ModItems.gemOnyx, 's', Items.stick);
		GameRegistry.addRecipe(new ItemStack(ModTools.onyxAxe), "oo", "os", " s", 'o', ModItems.gemOnyx, 's', Items.stick);
		GameRegistry.addRecipe(new ItemStack(ModTools.onyxSword), "o", "o", "s", 'o', ModItems.gemOnyx, 's', Items.stick);
		GameRegistry.addRecipe(new ItemStack(ModTools.onyxShovel), "o", "s", "s", 'o', ModItems.gemOnyx, 's', Items.stick);
		GameRegistry.addRecipe(new ItemStack(ModTools.onyxHoe), "oo", " s", " s", 'o', ModItems.gemOnyx, 's', Items.stick);
		GameRegistry.addRecipe(new ItemStack(ModTools.rubyPickaxe), "rrr", " s ", " s ", 'r', ModItems.gemRuby, 's', Items.stick);
		GameRegistry.addRecipe(new ItemStack(ModTools.rubyAxe), "rr", "rs", " s", 'r', ModItems.gemRuby, 's', Items.stick);
		GameRegistry.addRecipe(new ItemStack(ModTools.rubySword), "r", "r", "s", 'r', ModItems.gemRuby, 's', Items.stick);
		GameRegistry.addRecipe(new ItemStack(ModTools.rubyShovel), "r", "s", "s", 'r', ModItems.gemRuby, 's', Items.stick);
		GameRegistry.addRecipe(new ItemStack(ModTools.rubyHoe), "rr", " s", " s", 'r', ModItems.gemRuby, 's', Items.stick);
		// Misc
		GameRegistry.addRecipe(new ItemStack(ModItems.paintbrush), "  w", " i ", "s  ", 's', Items.stick, 'i', Items.iron_ingot, 'w', Items.wheat);
		GameRegistry.addRecipe(new ItemStack(ModItems.paintbrush), "w  ", " i ", "  s", 's', Items.stick, 'i', Items.iron_ingot, 'w', Items.wheat);
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.paintbrushColoured, 1, 0), new ItemStack(ModItems.paintbrush, 1, 0), new ItemStack(Items.dye, 1, 15));
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.paintbrushColoured, 1, 1), new ItemStack(ModItems.paintbrush, 1, 0), new ItemStack(Items.dye, 1, 14));
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.paintbrushColoured, 1, 2), new ItemStack(ModItems.paintbrush, 1, 0), new ItemStack(Items.dye, 1, 13));
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.paintbrushColoured, 1, 3), new ItemStack(ModItems.paintbrush, 1, 0), new ItemStack(Items.dye, 1, 12));
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.paintbrushColoured, 1, 4), new ItemStack(ModItems.paintbrush, 1, 0), new ItemStack(Items.dye, 1, 11));
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.paintbrushColoured, 1, 5), new ItemStack(ModItems.paintbrush, 1, 0), new ItemStack(Items.dye, 1, 10));
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.paintbrushColoured, 1, 6), new ItemStack(ModItems.paintbrush, 1, 0), new ItemStack(Items.dye, 1, 9));
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.paintbrushColoured, 1, 7), new ItemStack(ModItems.paintbrush, 1, 0), new ItemStack(Items.dye, 1, 8));
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.paintbrushColoured, 1, 8), new ItemStack(ModItems.paintbrush, 1, 0), new ItemStack(Items.dye, 1, 7));
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.paintbrushColoured, 1, 9), new ItemStack(ModItems.paintbrush, 1, 0), new ItemStack(Items.dye, 1, 6));
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.paintbrushColoured, 1, 10), new ItemStack(ModItems.paintbrush, 1, 0), new ItemStack(Items.dye, 1, 5));
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.paintbrushColoured, 1, 11), new ItemStack(ModItems.paintbrush, 1, 0), new ItemStack(Items.dye, 1, 4));
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.paintbrushColoured, 1, 12), new ItemStack(ModItems.paintbrush, 1, 0), new ItemStack(Items.dye, 1, 3));
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.paintbrushColoured, 1, 13), new ItemStack(ModItems.paintbrush, 1, 0), new ItemStack(Items.dye, 1, 2));
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.paintbrushColoured, 1, 14), new ItemStack(ModItems.paintbrush, 1, 0), new ItemStack(Items.dye, 1, 1));
		GameRegistry.addShapelessRecipe(new ItemStack(ModItems.paintbrushColoured, 1, 15), new ItemStack(ModItems.paintbrush, 1, 0), new ItemStack(Items.dye, 1, 0));
		// Bricks
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 1, 0), new ItemStack(ModItems.paintbrushColoured, 1, 0), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 1, 1), new ItemStack(ModItems.paintbrushColoured, 1, 1), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 1, 2), new ItemStack(ModItems.paintbrushColoured, 1, 2), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 1, 3), new ItemStack(ModItems.paintbrushColoured, 1, 3), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 1, 4), new ItemStack(ModItems.paintbrushColoured, 1, 4), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 1, 5), new ItemStack(ModItems.paintbrushColoured, 1, 5), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 1, 6), new ItemStack(ModItems.paintbrushColoured, 1, 6), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 1, 7), new ItemStack(ModItems.paintbrushColoured, 1, 7), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 1, 8), new ItemStack(ModItems.paintbrushColoured, 1, 8), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 1, 9), new ItemStack(ModItems.paintbrushColoured, 1, 9), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 1, 10), new ItemStack(ModItems.paintbrushColoured, 1, 10), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 1, 11), new ItemStack(ModItems.paintbrushColoured, 1, 11), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 1, 12), new ItemStack(ModItems.paintbrushColoured, 1, 12), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 1, 13), new ItemStack(ModItems.paintbrushColoured, 1, 13), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 1, 14), new ItemStack(ModItems.paintbrushColoured, 1, 14), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 1, 15), new ItemStack(ModItems.paintbrushColoured, 1, 15), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 2, 0), new ItemStack(ModItems.paintbrushColoured, 1, 0), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 2, 1), new ItemStack(ModItems.paintbrushColoured, 1, 1), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 2, 2), new ItemStack(ModItems.paintbrushColoured, 1, 2), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 2, 3), new ItemStack(ModItems.paintbrushColoured, 1, 3), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 2, 4), new ItemStack(ModItems.paintbrushColoured, 1, 4), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 2, 5), new ItemStack(ModItems.paintbrushColoured, 1, 5), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 2, 6), new ItemStack(ModItems.paintbrushColoured, 1, 6), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 2, 7), new ItemStack(ModItems.paintbrushColoured, 1, 7), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 2, 8), new ItemStack(ModItems.paintbrushColoured, 1, 8), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 2, 9), new ItemStack(ModItems.paintbrushColoured, 1, 9), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 2, 10), new ItemStack(ModItems.paintbrushColoured, 1, 10), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 2, 11), new ItemStack(ModItems.paintbrushColoured, 1, 11), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 2, 12), new ItemStack(ModItems.paintbrushColoured, 1, 12), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 2, 13), new ItemStack(ModItems.paintbrushColoured, 1, 13), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 2, 14), new ItemStack(ModItems.paintbrushColoured, 1, 14), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 2, 15), new ItemStack(ModItems.paintbrushColoured, 1, 15), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 3, 0), new ItemStack(ModItems.paintbrushColoured, 1, 0), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 3, 1), new ItemStack(ModItems.paintbrushColoured, 1, 1), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 3, 2), new ItemStack(ModItems.paintbrushColoured, 1, 2), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 3, 3), new ItemStack(ModItems.paintbrushColoured, 1, 3), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 3, 4), new ItemStack(ModItems.paintbrushColoured, 1, 4), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 3, 5), new ItemStack(ModItems.paintbrushColoured, 1, 5), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 3, 6), new ItemStack(ModItems.paintbrushColoured, 1, 6), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 3, 7), new ItemStack(ModItems.paintbrushColoured, 1, 7), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 3, 8), new ItemStack(ModItems.paintbrushColoured, 1, 8), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 3, 9), new ItemStack(ModItems.paintbrushColoured, 1, 9), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 3, 10), new ItemStack(ModItems.paintbrushColoured, 1, 10), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 3, 11), new ItemStack(ModItems.paintbrushColoured, 1, 11), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 3, 12), new ItemStack(ModItems.paintbrushColoured, 1, 12), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 3, 13), new ItemStack(ModItems.paintbrushColoured, 1, 13), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 3, 14), new ItemStack(ModItems.paintbrushColoured, 1, 14), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 3, 15), new ItemStack(ModItems.paintbrushColoured, 1, 15), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 4, 0), new ItemStack(ModItems.paintbrushColoured, 1, 0), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 4, 1), new ItemStack(ModItems.paintbrushColoured, 1, 1), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 4, 2), new ItemStack(ModItems.paintbrushColoured, 1, 2), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 4, 3), new ItemStack(ModItems.paintbrushColoured, 1, 3), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 4, 4), new ItemStack(ModItems.paintbrushColoured, 1, 4), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 4, 5), new ItemStack(ModItems.paintbrushColoured, 1, 5), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 4, 6), new ItemStack(ModItems.paintbrushColoured, 1, 6), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 4, 7), new ItemStack(ModItems.paintbrushColoured, 1, 7), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 4, 8), new ItemStack(ModItems.paintbrushColoured, 1, 8), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 4, 9), new ItemStack(ModItems.paintbrushColoured, 1, 9), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 4, 10), new ItemStack(ModItems.paintbrushColoured, 1, 10), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 4, 11), new ItemStack(ModItems.paintbrushColoured, 1, 11), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 4, 12), new ItemStack(ModItems.paintbrushColoured, 1, 12), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 4, 13), new ItemStack(ModItems.paintbrushColoured, 1, 13), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 4, 14), new ItemStack(ModItems.paintbrushColoured, 1, 14), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 4, 15), new ItemStack(ModItems.paintbrushColoured, 1, 15), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 5, 0), new ItemStack(ModItems.paintbrushColoured, 1, 0), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 5, 1), new ItemStack(ModItems.paintbrushColoured, 1, 1), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 5, 2), new ItemStack(ModItems.paintbrushColoured, 1, 2), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 5, 3), new ItemStack(ModItems.paintbrushColoured, 1, 3), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 5, 4), new ItemStack(ModItems.paintbrushColoured, 1, 4), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 5, 5), new ItemStack(ModItems.paintbrushColoured, 1, 5), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 5, 6), new ItemStack(ModItems.paintbrushColoured, 1, 6), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 5, 7), new ItemStack(ModItems.paintbrushColoured, 1, 7), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 5, 8), new ItemStack(ModItems.paintbrushColoured, 1, 8), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 5, 9), new ItemStack(ModItems.paintbrushColoured, 1, 9), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 5, 10), new ItemStack(ModItems.paintbrushColoured, 1, 10), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 5, 11), new ItemStack(ModItems.paintbrushColoured, 1, 11), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 5, 12), new ItemStack(ModItems.paintbrushColoured, 1, 12), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 5, 13), new ItemStack(ModItems.paintbrushColoured, 1, 13), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 5, 14), new ItemStack(ModItems.paintbrushColoured, 1, 14), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 5, 15), new ItemStack(ModItems.paintbrushColoured, 1, 15), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 6, 0), new ItemStack(ModItems.paintbrushColoured, 1, 0), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 6, 1), new ItemStack(ModItems.paintbrushColoured, 1, 1), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 6, 2), new ItemStack(ModItems.paintbrushColoured, 1, 2), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 6, 3), new ItemStack(ModItems.paintbrushColoured, 1, 3), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 6, 4), new ItemStack(ModItems.paintbrushColoured, 1, 4), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 6, 5), new ItemStack(ModItems.paintbrushColoured, 1, 5), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 6, 6), new ItemStack(ModItems.paintbrushColoured, 1, 6), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 6, 7), new ItemStack(ModItems.paintbrushColoured, 1, 7), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 6, 8), new ItemStack(ModItems.paintbrushColoured, 1, 8), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 6, 9), new ItemStack(ModItems.paintbrushColoured, 1, 9), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 6, 10), new ItemStack(ModItems.paintbrushColoured, 1, 10), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 6, 11), new ItemStack(ModItems.paintbrushColoured, 1, 11), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 6, 12), new ItemStack(ModItems.paintbrushColoured, 1, 12), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 6, 13), new ItemStack(ModItems.paintbrushColoured, 1, 13), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 6, 14), new ItemStack(ModItems.paintbrushColoured, 1, 14), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 6, 15), new ItemStack(ModItems.paintbrushColoured, 1, 15), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 7, 0), new ItemStack(ModItems.paintbrushColoured, 1, 0), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 7, 1), new ItemStack(ModItems.paintbrushColoured, 1, 1), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 7, 2), new ItemStack(ModItems.paintbrushColoured, 1, 2), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 7, 3), new ItemStack(ModItems.paintbrushColoured, 1, 3), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 7, 4), new ItemStack(ModItems.paintbrushColoured, 1, 4), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 7, 5), new ItemStack(ModItems.paintbrushColoured, 1, 5), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 7, 6), new ItemStack(ModItems.paintbrushColoured, 1, 6), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 7, 7), new ItemStack(ModItems.paintbrushColoured, 1, 7), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 7, 8), new ItemStack(ModItems.paintbrushColoured, 1, 8), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 7, 9), new ItemStack(ModItems.paintbrushColoured, 1, 9), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 7, 10), new ItemStack(ModItems.paintbrushColoured, 1, 10), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 7, 11), new ItemStack(ModItems.paintbrushColoured, 1, 11), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 7, 12), new ItemStack(ModItems.paintbrushColoured, 1, 12), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 7, 13), new ItemStack(ModItems.paintbrushColoured, 1, 13), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 7, 14), new ItemStack(ModItems.paintbrushColoured, 1, 14), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 7, 15), new ItemStack(ModItems.paintbrushColoured, 1, 15), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 8, 0), new ItemStack(ModItems.paintbrushColoured, 1, 0), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 8, 1), new ItemStack(ModItems.paintbrushColoured, 1, 1), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 8, 2), new ItemStack(ModItems.paintbrushColoured, 1, 2), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 8, 3), new ItemStack(ModItems.paintbrushColoured, 1, 3), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 8, 4), new ItemStack(ModItems.paintbrushColoured, 1, 4), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 8, 5), new ItemStack(ModItems.paintbrushColoured, 1, 5), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 8, 6), new ItemStack(ModItems.paintbrushColoured, 1, 6), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 8, 7), new ItemStack(ModItems.paintbrushColoured, 1, 7), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 8, 8), new ItemStack(ModItems.paintbrushColoured, 1, 8), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 8, 9), new ItemStack(ModItems.paintbrushColoured, 1, 9), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 8, 10), new ItemStack(ModItems.paintbrushColoured, 1, 10), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 8, 11), new ItemStack(ModItems.paintbrushColoured, 1, 11), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 8, 12), new ItemStack(ModItems.paintbrushColoured, 1, 12), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 8, 13), new ItemStack(ModItems.paintbrushColoured, 1, 13), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 8, 14), new ItemStack(ModItems.paintbrushColoured, 1, 14), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.brickColoured, 8, 15), new ItemStack(ModItems.paintbrushColoured, 1, 15), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block), new ItemStack(Blocks.brick_block));
		// Planks
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.cherryPlanks, 4), ModBlocks.cherryWood);
		GameRegistry.addShapelessRecipe(new ItemStack(ModBlocks.rubberPlanks, 4), ModBlocks.rubberWood);
		// Machine Blocks
		GameRegistry.addRecipe(new ItemStack(ModBlocks.machineBlock), "pip", "ibi", "pip", 'p', ModItems.plateIron, 'i', Items.iron_ingot, 'b', ModBlocks.compressedIronBlock);
		GameRegistry.addRecipe(new ItemStack(ModBlocks.machineBlockSteel), "pip", "ibi", "pip", 'p', ModItems.plateSteel, 'i', ModItems.ingotSteel, 'b', ModBlocks.machineBlock);
		GameRegistry.addRecipe(new ItemStack(ModBlocks.machineBlockStrengthened), "pip", "ibi", "pip", 'p', ModItems.plateObsidian, 'i', ModBlocks.blockPureObsidian, 'b', ModBlocks.machineBlockSteel);
		GameRegistry.addRecipe(new ItemStack(ModBlocks.machineBlockReinforced), "pip", "ibi", "pip", 'p', ModItems.plateObsidian, 'i', ModBlocks.blockEnrichedObsidian, 'b', ModBlocks.machineBlockStrengthened);
		GameRegistry.addRecipe(new ItemStack(ModBlocks.machineBlockImbued), "pip", "ibi", "pip", 'p', ModItems.shardTrytementium, 'i', ModItems.shardUnobtanium, 'b', ModBlocks.machineBlockReinforced);
		GameRegistry.addRecipe(new ItemStack(ModBlocks.machineBlockFluxed), "pip", "ibi", "pip", 'p', ModItems.ylvoltium, 'i', ModItems.ylvoltiumFluxed, 'b', ModBlocks.machineBlockImbued);
		// Stairs & Slabs
		GameRegistry.addRecipe(new ItemStack(ModBlocks.cherryStairs, 4), "w  ", "ww ", "www", 'w', ModBlocks.cherryPlanks);
		GameRegistry.addRecipe(new ItemStack(ModBlocks.rubberStairs, 4), "w  ", "ww ", "www", 'w', ModBlocks.rubberPlanks);
		GameRegistry.addRecipe(new ItemStack(ModBlocks.cherrySlab, 6), "   ", "   ", "www", 'w', ModBlocks.cherryPlanks);
		GameRegistry.addRecipe(new ItemStack(ModBlocks.rubberSlab, 6), "   ", "   ", "www", 'w', ModBlocks.rubberPlanks);
		// Smelting Ores
		GameRegistry.addSmelting(ModBlocks.oreOnyx, new ItemStack(ModItems.gemOnyx), 5);
		GameRegistry.addSmelting(ModBlocks.oreRuby, new ItemStack(ModItems.gemRuby), 5);
		GameRegistry.addSmelting(ModBlocks.oreSapphire, new ItemStack(ModItems.gemSapphire), 5);
		GameRegistry.addSmelting(ModBlocks.oreCitrine, new ItemStack(ModItems.gemCitrine), 5);
		GameRegistry.addSmelting(ModBlocks.oreJade, new ItemStack(ModItems.gemJade), 5);
		GameRegistry.addSmelting(ModBlocks.oreAmethyst, new ItemStack(ModItems.gemAmethyst), 5);
		GameRegistry.addSmelting(ModBlocks.oreCarnelian, new ItemStack(ModItems.gemCarnelian), 5);
		GameRegistry.addSmelting(ModBlocks.oreAmazonite, new ItemStack(ModItems.gemAmazonite), 5);
		GameRegistry.addSmelting(ModBlocks.oreGarnet, new ItemStack(ModItems.gemGarnet), 5);
		GameRegistry.addSmelting(ModBlocks.oreKunzite, new ItemStack(ModItems.gemKunzite), 5);
		GameRegistry.addSmelting(ModBlocks.oreAquamarine, new ItemStack(ModItems.gemAquamarine), 5);
		GameRegistry.addSmelting(ModBlocks.oreVoidium, new ItemStack(ModItems.voidium), 5);
		GameRegistry.addSmelting(ModBlocks.oreVoidiumBedrock, new ItemStack(ModItems.voidium), 5);
		GameRegistry.addSmelting(ModBlocks.oreFyrestone, new ItemStack(ModItems.fyrestone), 5);
		GameRegistry.addSmelting(ModBlocks.oreTin, new ItemStack(ModItems.ingotTin), 5);
		GameRegistry.addSmelting(ModBlocks.oreCopper, new ItemStack(ModItems.ingotCopper), 5);
		GameRegistry.addSmelting(ModBlocks.oreSilver, new ItemStack(ModItems.ingotSilver), 5);
		GameRegistry.addSmelting(ModBlocks.oreLead, new ItemStack(ModItems.ingotLead), 5);
		GameRegistry.addSmelting(ModBlocks.orePlatinum, new ItemStack(ModItems.ingotPlatinum), 5);
		GameRegistry.addSmelting(ModBlocks.oreMalagnite, new ItemStack(ModItems.ingotMalagnite), 5);
		GameRegistry.addSmelting(ModBlocks.oreTrytementium, new ItemStack(ModItems.trytementium), 5);
		GameRegistry.addSmelting(ModBlocks.oreTitanium, new ItemStack(ModItems.ingotTitanium), 5);
		GameRegistry.addSmelting(ModBlocks.oreIridium, new ItemStack(ModItems.iridium), 5);
		GameRegistry.addSmelting(ModBlocks.oreUranium, new ItemStack(ModItems.uranium), 5);
		GameRegistry.addSmelting(ModBlocks.oreAluminium, new ItemStack(ModItems.ingotAluminium), 5);
		GameRegistry.addSmelting(ModBlocks.oreZinc, new ItemStack(ModItems.ingotZinc), 5);
		GameRegistry.addSmelting(ModBlocks.oreTopaz, new ItemStack(ModItems.gemTopaz), 5);
		GameRegistry.addSmelting(ModBlocks.orePlutonium, new ItemStack(ModItems.plutonium), 5);
		GameRegistry.addSmelting(ModBlocks.oreChromium, new ItemStack(ModItems.ingotChromium), 5);
		GameRegistry.addSmelting(ModBlocks.oreCobalt, new ItemStack(ModItems.ingotCobalt), 5);
		GameRegistry.addSmelting(ModBlocks.oreManganese, new ItemStack(ModItems.ingotManganese), 5);
		GameRegistry.addSmelting(ModBlocks.oreMithril, new ItemStack(ModItems.ingotMithril), 5);
		GameRegistry.addSmelting(ModBlocks.oreNickel, new ItemStack(ModItems.ingotNickel), 5);
		GameRegistry.addSmelting(ModBlocks.oreRhodium, new ItemStack(ModItems.ingotRhodium), 5);
		GameRegistry.addSmelting(ModBlocks.oreRubium, new ItemStack(ModItems.ingotRubium), 5);
		GameRegistry.addSmelting(ModBlocks.oreRunite, new ItemStack(ModItems.ingotRunite), 5);
		GameRegistry.addSmelting(ModBlocks.oreSilicon, new ItemStack(ModItems.ingotSilicon), 5);
		GameRegistry.addSmelting(ModBlocks.oreTungsten, new ItemStack(ModItems.ingotTungsten), 5);
		GameRegistry.addSmelting(ModBlocks.oreAdamanite, new ItemStack(ModItems.ingotAdamanite), 5);
		GameRegistry.addSmelting(ModBlocks.oreBlurite, new ItemStack(ModItems.ingotBlurite), 5);
		GameRegistry.addSmelting(ModBlocks.oreDaeyalt, new ItemStack(ModItems.ingotDaeyalt), 5);
		GameRegistry.addSmelting(ModBlocks.oreLunar, new ItemStack(ModItems.ingotLunar), 5);
		// Smelting Dusts
		GameRegistry.addSmelting(ModItems.dustOnyx, new ItemStack(ModItems.gemOnyx), 5);
		GameRegistry.addSmelting(ModItems.dustRuby, new ItemStack(ModItems.gemRuby), 5);
		GameRegistry.addSmelting(ModItems.dustSapphire, new ItemStack(ModItems.gemSapphire), 5);
		GameRegistry.addSmelting(ModItems.dustCitrine, new ItemStack(ModItems.gemCitrine), 5);
		GameRegistry.addSmelting(ModItems.dustJade, new ItemStack(ModItems.gemJade), 5);
		GameRegistry.addSmelting(ModItems.dustAmethyst, new ItemStack(ModItems.gemAmethyst), 5);
		GameRegistry.addSmelting(ModItems.dustCarnelian, new ItemStack(ModItems.gemCarnelian), 5);
		GameRegistry.addSmelting(ModItems.dustAmazonite, new ItemStack(ModItems.gemAmazonite), 5);
		GameRegistry.addSmelting(ModItems.dustGarnet, new ItemStack(ModItems.gemGarnet), 5);
		GameRegistry.addSmelting(ModItems.dustKunzite, new ItemStack(ModItems.gemKunzite), 5);
		GameRegistry.addSmelting(ModItems.dustAquamarine, new ItemStack(ModItems.gemAquamarine), 5);
		GameRegistry.addSmelting(ModItems.dustVoidium, new ItemStack(ModItems.voidium), 5);
		GameRegistry.addSmelting(ModItems.dustFyrestone, new ItemStack(ModItems.fyrestone), 5);
		GameRegistry.addSmelting(ModItems.dustTin, new ItemStack(ModItems.ingotTin), 5);
		GameRegistry.addSmelting(ModItems.dustCopper, new ItemStack(ModItems.ingotCopper), 5);
		GameRegistry.addSmelting(ModItems.dustSilver, new ItemStack(ModItems.ingotSilver), 5);
		GameRegistry.addSmelting(ModItems.dustLead, new ItemStack(ModItems.ingotLead), 5);
		GameRegistry.addSmelting(ModItems.dustPlatinum, new ItemStack(ModItems.ingotPlatinum), 5);
		GameRegistry.addSmelting(ModItems.dustMalagnite, new ItemStack(ModItems.ingotMalagnite), 5);
		GameRegistry.addSmelting(ModItems.dustTrytementium, new ItemStack(ModItems.trytementium), 5);
		GameRegistry.addSmelting(ModItems.dustTitanium, new ItemStack(ModItems.ingotTitanium), 5);
		GameRegistry.addSmelting(ModItems.dustIridium, new ItemStack(ModItems.iridium), 5);
		GameRegistry.addSmelting(ModItems.dustUranium, new ItemStack(ModItems.uranium), 5);
		GameRegistry.addSmelting(ModItems.dustAluminium, new ItemStack(ModItems.ingotAluminium), 5);
		GameRegistry.addSmelting(ModItems.dustZinc, new ItemStack(ModItems.ingotZinc), 5);
		GameRegistry.addSmelting(ModItems.dustTopaz, new ItemStack(ModItems.gemTopaz), 5);
		GameRegistry.addSmelting(ModItems.dustPlutonium, new ItemStack(ModItems.plutonium), 5);
		GameRegistry.addSmelting(ModItems.dustChromium, new ItemStack(ModItems.ingotChromium), 5);
		GameRegistry.addSmelting(ModItems.dustCobalt, new ItemStack(ModItems.ingotCobalt), 5);
		GameRegistry.addSmelting(ModItems.dustManganese, new ItemStack(ModItems.ingotManganese), 5);
		GameRegistry.addSmelting(ModItems.dustMithril, new ItemStack(ModItems.ingotMithril), 5);
		GameRegistry.addSmelting(ModItems.dustNickel, new ItemStack(ModItems.ingotNickel), 5);
		GameRegistry.addSmelting(ModItems.dustRhodium, new ItemStack(ModItems.ingotRhodium), 5);
		GameRegistry.addSmelting(ModItems.dustRubium, new ItemStack(ModItems.ingotRubium), 5);
		GameRegistry.addSmelting(ModItems.dustRunite, new ItemStack(ModItems.ingotRunite), 5);
		GameRegistry.addSmelting(ModItems.dustSilicon, new ItemStack(ModItems.ingotSilicon), 5);
		GameRegistry.addSmelting(ModItems.dustTungsten, new ItemStack(ModItems.ingotTungsten), 5);
		GameRegistry.addSmelting(ModItems.dustAdamanite, new ItemStack(ModItems.ingotAdamanite), 5);
		GameRegistry.addSmelting(ModItems.dustBlurite, new ItemStack(ModItems.ingotBlurite), 5);
		GameRegistry.addSmelting(ModItems.dustDaeyalt, new ItemStack(ModItems.ingotDaeyalt), 5);
		GameRegistry.addSmelting(ModItems.dustLunar, new ItemStack(ModItems.ingotLunar), 5);
		// Misc Smelting
		GameRegistry.addSmelting(ModItems.resin, new ItemStack(ModItems.rubber), 5);
		GameRegistry.addSmelting(ModItems.fossilResin, new ItemStack(ModItems.rubber), 5);
		// Bonemeal
		GameRegistry.addShapelessRecipe(new ItemStack(Items.dye, 12, 15), new ItemStack(ModItems.fossil, 1, 0));
		GameRegistry.addShapelessRecipe(new ItemStack(Items.dye, 8, 15), new ItemStack(ModItems.fossil, 1, 1));
		GameRegistry.addShapelessRecipe(new ItemStack(Items.dye, 8, 15), new ItemStack(ModItems.fossil, 1, 2));
		GameRegistry.addShapelessRecipe(new ItemStack(Items.dye, 24, 15), new ItemStack(ModItems.fossil, 1, 3));
		GameRegistry.addShapelessRecipe(new ItemStack(Items.dye, 24, 15), new ItemStack(ModItems.fossil, 1, 4));
		GameRegistry.addShapelessRecipe(new ItemStack(Items.dye, 8, 15), new ItemStack(ModItems.fossil, 1, 5));
		
		LogHelper.info("Recipes initialised successfully!");
	}
}
