package com.shnupbups.allthethings.utility;

import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

import com.shnupbups.allthethings.init.ModBlocks;
import com.shnupbups.allthethings.init.ModItems;

public class PulverizingRecipes {

	public static ItemStack getPulverizeResult(ItemStack itemstack) {
		if(itemstack != null) {
			if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreAdamanite)) return new ItemStack(ModItems.dustAdamanite, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreAluminium)) return new ItemStack(ModItems.dustAluminium, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreBlurite)) return new ItemStack(ModItems.dustBlurite, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreChromium)) return new ItemStack(ModItems.dustChromium, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreCobalt)) return new ItemStack(ModItems.dustCobalt, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreCopper)) return new ItemStack(ModItems.dustCopper, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreDaeyalt)) return new ItemStack(ModItems.dustDaeyalt, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(Blocks.gold_ore)) return new ItemStack(ModItems.dustGold, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(Blocks.iron_ore)) return new ItemStack(ModItems.dustIron, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreLead)) return new ItemStack(ModItems.dustLead, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreLunar)) return new ItemStack(ModItems.dustLunar, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreMalagnite)) return new ItemStack(ModItems.dustMalagnite, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreManganese)) return new ItemStack(ModItems.dustManganese, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreMithril)) return new ItemStack(ModItems.dustMithril, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreNickel)) return new ItemStack(ModItems.dustNickel, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.orePlatinum)) return new ItemStack(ModItems.dustPlatinum, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreRhodium)) return new ItemStack(ModItems.dustRhodium, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreRubium)) return new ItemStack(ModItems.dustRubium, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreRunite)) return new ItemStack(ModItems.dustRunite, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreSilicon)) return new ItemStack(ModItems.dustSilicon, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreSilver)) return new ItemStack(ModItems.dustSilver, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreTin)) return new ItemStack(ModItems.dustTin, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreTitanium)) return new ItemStack(ModItems.dustTitanium, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreTungsten)) return new ItemStack(ModItems.dustTungsten, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreZinc)) return new ItemStack(ModItems.dustZinc, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreAmazonite)) return new ItemStack(ModItems.dustAmazonite, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreAmethyst)) return new ItemStack(ModItems.dustAmethyst, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreAquamarine)) return new ItemStack(ModItems.dustAquamarine, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreCarnelian)) return new ItemStack(ModItems.dustCarnelian, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreCitrine)) return new ItemStack(ModItems.dustCitrine, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(Blocks.diamond_ore)) return new ItemStack(ModItems.dustDiamond, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(Blocks.emerald_ore)) return new ItemStack(ModItems.dustEmerald, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreGarnet)) return new ItemStack(ModItems.dustGarnet, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreJade)) return new ItemStack(ModItems.dustJade, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreKunzite)) return new ItemStack(ModItems.dustKunzite, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(Blocks.quartz_ore)) return new ItemStack(ModItems.dustNetherQuartz, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreOnyx)) return new ItemStack(ModItems.dustOnyx, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreOpal)) return new ItemStack(ModItems.dustOpal, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreQuartz)) return new ItemStack(ModItems.dustQuartz, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreRuby)) return new ItemStack(ModItems.dustRuby, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreSapphire)) return new ItemStack(ModItems.dustSapphire, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreTopaz)) return new ItemStack(ModItems.dustTopaz, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreFyrestone)) return new ItemStack(ModItems.dustFyrestone, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreVoidium)) return new ItemStack(ModItems.dustVoidium, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreVoidiumBedrock)) return new ItemStack(ModItems.dustVoidium, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreIridium)) return new ItemStack(ModItems.dustIridium, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.orePlutonium)) return new ItemStack(ModItems.dustPlutonium, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreUranium)) return new ItemStack(ModItems.dustUranium, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(Blocks.coal_ore)) return new ItemStack(ModItems.dustCoal, 2);
			else if(itemstack.getItem() == Item.getItemFromBlock(Blocks.lapis_ore)) return new ItemStack(ModItems.dustLapis, 12);
			else if(itemstack.getItem() == Item.getItemFromBlock(Blocks.redstone_ore)) return new ItemStack(Items.redstone, 12);
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreTrytementium)) return new ItemStack(ModItems.dustTrytementium, 2);
			
			else if(itemstack.getItem() == ModItems.ingotAdamanite) return new ItemStack(ModItems.dustAdamanite);
			else if(itemstack.getItem() == ModItems.ingotAdamant) return new ItemStack(ModItems.dustAdamant);
			else if(itemstack.getItem() == ModItems.ingotAluminium) return new ItemStack(ModItems.dustAluminium);
			else if(itemstack.getItem() == ModItems.ingotBlurite) return new ItemStack(ModItems.dustBlurite);
			else if(itemstack.getItem() == ModItems.ingotBrass) return new ItemStack(ModItems.dustBrass);
			else if(itemstack.getItem() == ModItems.ingotChromium) return new ItemStack(ModItems.dustChromium);
			else if(itemstack.getItem() == ModItems.ingotCobalt) return new ItemStack(ModItems.dustCobalt);
			else if(itemstack.getItem() == ModItems.ingotCopper) return new ItemStack(ModItems.dustCopper);
			else if(itemstack.getItem() == ModItems.ingotDaeyalt) return new ItemStack(ModItems.dustDaeyalt);
			else if(itemstack.getItem() == ModItems.ingotElectrum) return new ItemStack(ModItems.dustElectrum);
			else if(itemstack.getItem() == Items.gold_ingot) return new ItemStack(ModItems.dustGold);
			else if(itemstack.getItem() == ModItems.ingotGoloid) return new ItemStack(ModItems.dustGoloid);
			else if(itemstack.getItem() == ModItems.ingotInvar) return new ItemStack(ModItems.dustInvar);
			else if(itemstack.getItem() == Items.iron_ingot) return new ItemStack(ModItems.dustIron);
			else if(itemstack.getItem() == ModItems.ingotLead) return new ItemStack(ModItems.dustLead);
			else if(itemstack.getItem() == ModItems.ingotLunar) return new ItemStack(ModItems.dustLunar);
			else if(itemstack.getItem() == ModItems.ingotMalagnite) return new ItemStack(ModItems.dustMalagnite);
			else if(itemstack.getItem() == ModItems.ingotManganese) return new ItemStack(ModItems.dustManganese);
			else if(itemstack.getItem() == ModItems.ingotMithril) return new ItemStack(ModItems.dustMithril);
			else if(itemstack.getItem() == ModItems.ingotNickel) return new ItemStack(ModItems.dustNickel);
			else if(itemstack.getItem() == ModItems.ingotPlatinum) return new ItemStack(ModItems.dustPlatinum);
			else if(itemstack.getItem() == ModItems.ingotRhodium) return new ItemStack(ModItems.dustRhodium);
			else if(itemstack.getItem() == ModItems.ingotRubium) return new ItemStack(ModItems.dustRubium);
			else if(itemstack.getItem() == ModItems.ingotRunite) return new ItemStack(ModItems.dustRunite);
			else if(itemstack.getItem() == ModItems.ingotSilicon) return new ItemStack(ModItems.dustSilicon);
			else if(itemstack.getItem() == ModItems.ingotSilver) return new ItemStack(ModItems.dustSilver);
			else if(itemstack.getItem() == ModItems.ingotSolder) return new ItemStack(ModItems.dustSolder);
			else if(itemstack.getItem() == ModItems.ingotSteel) return new ItemStack(ModItems.dustSteel);
			else if(itemstack.getItem() == ModItems.ingotTin) return new ItemStack(ModItems.dustTin);
			else if(itemstack.getItem() == ModItems.ingotTitanium) return new ItemStack(ModItems.dustTitanium);
			else if(itemstack.getItem() == ModItems.ingotTungsten) return new ItemStack(ModItems.dustTungsten);
			else if(itemstack.getItem() == ModItems.ingotZinc) return new ItemStack(ModItems.dustZinc);
			else if(itemstack.getItem() == ModItems.gemAmazonite) return new ItemStack(ModItems.dustAmazonite);
			else if(itemstack.getItem() == ModItems.gemAmber) return new ItemStack(ModItems.dustAmazonite);
			else if(itemstack.getItem() == ModItems.gemAmethyst) return new ItemStack(ModItems.dustAmethyst);
			else if(itemstack.getItem() == ModItems.gemAquamarine) return new ItemStack(ModItems.dustAquamarine);
			else if(itemstack.getItem() == ModItems.gemCarnelian) return new ItemStack(ModItems.dustCarnelian);
			else if(itemstack.getItem() == ModItems.gemCitrine) return new ItemStack(ModItems.dustCitrine);
			else if(itemstack.getItem() == Items.diamond) return new ItemStack(ModItems.dustDiamond);
			else if(itemstack.getItem() == Items.emerald) return new ItemStack(ModItems.dustEmerald);
			else if(itemstack.getItem() == ModItems.gemGarnet) return new ItemStack(ModItems.dustGarnet);
			else if(itemstack.getItem() == ModItems.gemJade) return new ItemStack(ModItems.dustJade);
			else if(itemstack.getItem() == ModItems.gemKunzite) return new ItemStack(ModItems.dustKunzite);
			else if(itemstack.getItem() == Items.quartz) return new ItemStack(ModItems.dustNetherQuartz);
			else if(itemstack.getItem() == ModItems.gemOnyx) return new ItemStack(ModItems.dustOnyx);
			else if(itemstack.getItem() == ModItems.gemOpal) return new ItemStack(ModItems.dustOpal);
			else if(itemstack.getItem() == ModItems.gemQuartz) return new ItemStack(ModItems.dustQuartz);
			else if(itemstack.getItem() == ModItems.gemRuby) return new ItemStack(ModItems.dustRuby);
			else if(itemstack.getItem() == ModItems.gemSapphire) return new ItemStack(ModItems.dustSapphire);
			else if(itemstack.getItem() == ModItems.gemTopaz) return new ItemStack(ModItems.dustTopaz);
			else if(itemstack.getItem() == ModItems.fyrestone) return new ItemStack(ModItems.dustFyrestone);
			else if(itemstack.getItem() == ModItems.voidium) return new ItemStack(ModItems.dustVoidium);
			else if(itemstack.getItem() == ModItems.iridium) return new ItemStack(ModItems.dustIridium);
			else if(itemstack.getItem() == ModItems.plutonium) return new ItemStack(ModItems.dustPlutonium);
			else if(itemstack.getItem() == ModItems.uranium) return new ItemStack(ModItems.dustUranium);
			else if(itemstack.getItem() == Items.coal) return new ItemStack(ModItems.dustCoal);
			else if(itemstack.getItem() == Items.dye && itemstack.getItemDamage() == 4) return new ItemStack(ModItems.dustLapis);
			else if(itemstack.getItem() == ModItems.trytementium) return new ItemStack(ModItems.dustTrytementium);
			else if(itemstack.getItem() == ModItems.unobtanium) return new ItemStack(ModItems.dustUnobtanium);
			
			else if(itemstack.getItem() == ModItems.clusterAdamanite) return new ItemStack(ModItems.dustAdamanite, 2);
			else if(itemstack.getItem() == ModItems.clusterAdamant) return new ItemStack(ModItems.dustAdamant, 2);
			else if(itemstack.getItem() == ModItems.clusterAluminium) return new ItemStack(ModItems.dustAluminium, 2);
			else if(itemstack.getItem() == ModItems.clusterBlurite) return new ItemStack(ModItems.dustBlurite, 2);
			else if(itemstack.getItem() == ModItems.clusterBrass) return new ItemStack(ModItems.dustBrass, 2);
			else if(itemstack.getItem() == ModItems.clusterChromium) return new ItemStack(ModItems.dustChromium, 2);
			else if(itemstack.getItem() == ModItems.clusterCobalt) return new ItemStack(ModItems.dustCobalt, 2);
			else if(itemstack.getItem() == ModItems.clusterCopper) return new ItemStack(ModItems.dustCopper, 2);
			else if(itemstack.getItem() == ModItems.clusterDaeyalt) return new ItemStack(ModItems.dustDaeyalt, 2);
			else if(itemstack.getItem() == ModItems.clusterElectrum) return new ItemStack(ModItems.dustElectrum, 2);
			else if(itemstack.getItem() == ModItems.clusterGold) return new ItemStack(ModItems.dustGold, 2);
			else if(itemstack.getItem() == ModItems.clusterGoloid) return new ItemStack(ModItems.dustGoloid, 2);
			else if(itemstack.getItem() == ModItems.clusterInvar) return new ItemStack(ModItems.dustInvar, 2);
			else if(itemstack.getItem() == ModItems.clusterIron) return new ItemStack(ModItems.dustIron, 2);
			else if(itemstack.getItem() == ModItems.clusterLead) return new ItemStack(ModItems.dustLead, 2);
			else if(itemstack.getItem() == ModItems.clusterLunar) return new ItemStack(ModItems.dustLunar, 2);
			else if(itemstack.getItem() == ModItems.clusterMalagnite) return new ItemStack(ModItems.dustMalagnite, 2);
			else if(itemstack.getItem() == ModItems.clusterManganese) return new ItemStack(ModItems.dustManganese, 2);
			else if(itemstack.getItem() == ModItems.clusterMithril) return new ItemStack(ModItems.dustMithril, 2);
			else if(itemstack.getItem() == ModItems.clusterNickel) return new ItemStack(ModItems.dustNickel, 2);
			else if(itemstack.getItem() == ModItems.clusterPlatinum) return new ItemStack(ModItems.dustPlatinum, 2);
			else if(itemstack.getItem() == ModItems.clusterRhodium) return new ItemStack(ModItems.dustRhodium, 2);
			else if(itemstack.getItem() == ModItems.clusterRubium) return new ItemStack(ModItems.dustRubium, 2);
			else if(itemstack.getItem() == ModItems.clusterRunite) return new ItemStack(ModItems.dustRunite, 2);
			else if(itemstack.getItem() == ModItems.clusterSilicon) return new ItemStack(ModItems.dustSilicon, 2);
			else if(itemstack.getItem() == ModItems.clusterSilver) return new ItemStack(ModItems.dustSilver, 2);
			else if(itemstack.getItem() == ModItems.clusterSolder) return new ItemStack(ModItems.dustSolder, 2);
			else if(itemstack.getItem() == ModItems.clusterSteel) return new ItemStack(ModItems.dustSteel, 2);
			else if(itemstack.getItem() == ModItems.clusterTin) return new ItemStack(ModItems.dustTin, 2);
			else if(itemstack.getItem() == ModItems.clusterTitanium) return new ItemStack(ModItems.dustTitanium, 2);
			else if(itemstack.getItem() == ModItems.clusterTungsten) return new ItemStack(ModItems.dustTungsten, 2);
			else if(itemstack.getItem() == ModItems.clusterZinc) return new ItemStack(ModItems.dustZinc, 2);
			else if(itemstack.getItem() == ModItems.clusterAmazonite) return new ItemStack(ModItems.dustAmazonite, 2);
			else if(itemstack.getItem() == ModItems.clusterAmber) return new ItemStack(ModItems.dustAmazonite, 2);
			else if(itemstack.getItem() == ModItems.clusterAmethyst) return new ItemStack(ModItems.dustAmethyst, 2);
			else if(itemstack.getItem() == ModItems.clusterAquamarine) return new ItemStack(ModItems.dustAquamarine, 2);
			else if(itemstack.getItem() == ModItems.clusterCarnelian) return new ItemStack(ModItems.dustCarnelian, 2);
			else if(itemstack.getItem() == ModItems.clusterCitrine) return new ItemStack(ModItems.dustCitrine, 2);
			else if(itemstack.getItem() == ModItems.clusterDiamond) return new ItemStack(ModItems.dustDiamond, 2);
			else if(itemstack.getItem() == ModItems.clusterEmerald) return new ItemStack(ModItems.dustEmerald, 2);
			else if(itemstack.getItem() == ModItems.clusterGarnet) return new ItemStack(ModItems.dustGarnet, 2);
			else if(itemstack.getItem() == ModItems.clusterJade) return new ItemStack(ModItems.dustJade, 2);
			else if(itemstack.getItem() == ModItems.clusterKunzite) return new ItemStack(ModItems.dustKunzite, 2);
			else if(itemstack.getItem() == ModItems.clusterNetherQuartz) return new ItemStack(ModItems.dustNetherQuartz, 2);
			else if(itemstack.getItem() == ModItems.clusterOnyx) return new ItemStack(ModItems.dustOnyx, 2);
			else if(itemstack.getItem() == ModItems.clusterOpal) return new ItemStack(ModItems.dustOpal, 2);
			else if(itemstack.getItem() == ModItems.clusterQuartz) return new ItemStack(ModItems.dustQuartz, 2);
			else if(itemstack.getItem() == ModItems.clusterRuby) return new ItemStack(ModItems.dustRuby, 2);
			else if(itemstack.getItem() == ModItems.clusterSapphire) return new ItemStack(ModItems.dustSapphire, 2);
			else if(itemstack.getItem() == ModItems.clusterTopaz) return new ItemStack(ModItems.dustTopaz, 2);
			else if(itemstack.getItem() == ModItems.clusterFyrestone) return new ItemStack(ModItems.dustFyrestone, 2);
			else if(itemstack.getItem() == ModItems.clusterVoidium) return new ItemStack(ModItems.dustVoidium, 2);
			else if(itemstack.getItem() == ModItems.clusterIridium) return new ItemStack(ModItems.dustIridium, 2);
			else if(itemstack.getItem() == ModItems.clusterPlutonium) return new ItemStack(ModItems.dustPlutonium, 2);
			else if(itemstack.getItem() == ModItems.clusterUranium) return new ItemStack(ModItems.dustUranium, 2);
			else if(itemstack.getItem() == ModItems.clusterCoal) return new ItemStack(ModItems.dustCoal, 2);
			else if(itemstack.getItem() == ModItems.clusterLapis) return new ItemStack(ModItems.dustLapis, 4);
			else if(itemstack.getItem() == ModItems.clusterRedstone) return new ItemStack(Items.redstone, 4);
			else if(itemstack.getItem() == ModItems.clusterTrytementium) return new ItemStack(ModItems.dustTrytementium, 2);
			else if(itemstack.getItem() == ModItems.clusterUnobtanium) return new ItemStack(ModItems.dustUnobtanium, 2);
			
			else if(itemstack.getItem() == Items.bone) return new ItemStack(Items.dye, 6, 15);
			else if(itemstack.getItem() == ModItems.fossil && itemstack.getItemDamage() == 0) return new ItemStack(Items.dye, 24, 15);
			else if(itemstack.getItem() == ModItems.fossil && itemstack.getItemDamage() == 1) return new ItemStack(Items.dye, 16, 15);
			else if(itemstack.getItem() == ModItems.fossil && itemstack.getItemDamage() == 2) return new ItemStack(Items.dye, 16, 15);
			else if(itemstack.getItem() == ModItems.fossil && itemstack.getItemDamage() == 3) return new ItemStack(Items.dye, 48, 15);
			else if(itemstack.getItem() == ModItems.fossil && itemstack.getItemDamage() == 4) return new ItemStack(Items.dye, 48, 15);
			else if(itemstack.getItem() == ModItems.fossil && itemstack.getItemDamage() == 5) return new ItemStack(Items.dye, 16, 15);
			
			else if(itemstack.getItem() == Items.bread) return new ItemStack(ModItems.flour, 1);
			else if(itemstack.getItem() == Items.wheat) return new ItemStack(ModItems.flour, 2);
		} return null;
	}
	
	private static boolean stackSizeIsMoreOrEqual(ItemStack itemstack, int stackSize) {
		return itemstack.stackSize >= stackSize;
	}
	
	public static int getStackSizeToDecrease(ItemStack itemstack) {
		return 1;
	}
	
	public static int getPulverizeAmount(ItemStack itemstack) {
		if(itemstack != null) {
			if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreAdamanite)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreAluminium)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreBlurite)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreChromium)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreCobalt)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreCopper)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreDaeyalt)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(Blocks.gold_ore)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(Blocks.iron_ore)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreLead)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreLunar)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreMalagnite)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreManganese)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreMithril)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreNickel)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.orePlatinum)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreRhodium)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreRubium)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreRunite)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreSilicon)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreSilver)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreTin)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreTitanium)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreTungsten)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreZinc)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreAmazonite)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreAmethyst)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreAquamarine)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreCarnelian)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreCitrine)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(Blocks.diamond_ore)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(Blocks.emerald_ore)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreGarnet)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreJade)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreKunzite)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(Blocks.quartz_ore)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreOnyx)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreOpal)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreQuartz)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreRuby)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreSapphire)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreTopaz)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreFyrestone)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreVoidium)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreVoidiumBedrock)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreIridium)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.orePlutonium)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreUranium)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(Blocks.coal_ore)) return 2;
			else if(itemstack.getItem() == Item.getItemFromBlock(Blocks.lapis_ore)) return 12;
			else if(itemstack.getItem() == Item.getItemFromBlock(Blocks.redstone_ore)) return 12;
			else if(itemstack.getItem() == Item.getItemFromBlock(ModBlocks.oreTrytementium)) return 2;
			
			else if(itemstack.getItem() == ModItems.ingotAdamanite) return 1;
			else if(itemstack.getItem() == ModItems.ingotAdamant) return 1;
			else if(itemstack.getItem() == ModItems.ingotAluminium) return 1;
			else if(itemstack.getItem() == ModItems.ingotBlurite) return 1;
			else if(itemstack.getItem() == ModItems.ingotBrass) return 1;
			else if(itemstack.getItem() == ModItems.ingotChromium) return 1;
			else if(itemstack.getItem() == ModItems.ingotCobalt) return 1;
			else if(itemstack.getItem() == ModItems.ingotCopper) return 1;
			else if(itemstack.getItem() == ModItems.ingotDaeyalt) return 1;
			else if(itemstack.getItem() == ModItems.ingotElectrum) return 1;
			else if(itemstack.getItem() == Items.gold_ingot) return 1;
			else if(itemstack.getItem() == ModItems.ingotGoloid) return 1;
			else if(itemstack.getItem() == ModItems.ingotInvar) return 1;
			else if(itemstack.getItem() == Items.iron_ingot) return 1;
			else if(itemstack.getItem() == ModItems.ingotLead) return 1;
			else if(itemstack.getItem() == ModItems.ingotLunar) return 1;
			else if(itemstack.getItem() == ModItems.ingotMalagnite) return 1;
			else if(itemstack.getItem() == ModItems.ingotManganese) return 1;
			else if(itemstack.getItem() == ModItems.ingotMithril) return 1;
			else if(itemstack.getItem() == ModItems.ingotNickel) return 1;
			else if(itemstack.getItem() == ModItems.ingotPlatinum) return 1;
			else if(itemstack.getItem() == ModItems.ingotRhodium) return 1;
			else if(itemstack.getItem() == ModItems.ingotRubium) return 1;
			else if(itemstack.getItem() == ModItems.ingotRunite) return 1;
			else if(itemstack.getItem() == ModItems.ingotSilicon) return 1;
			else if(itemstack.getItem() == ModItems.ingotSilver) return 1;
			else if(itemstack.getItem() == ModItems.ingotSolder) return 1;
			else if(itemstack.getItem() == ModItems.ingotSteel) return 1;
			else if(itemstack.getItem() == ModItems.ingotTin) return 1;
			else if(itemstack.getItem() == ModItems.ingotTitanium) return 1;
			else if(itemstack.getItem() == ModItems.ingotTungsten) return 1;
			else if(itemstack.getItem() == ModItems.ingotZinc) return 1;
			else if(itemstack.getItem() == ModItems.gemAmazonite) return 1;
			else if(itemstack.getItem() == ModItems.gemAmber) return 1;
			else if(itemstack.getItem() == ModItems.gemAmethyst) return 1;
			else if(itemstack.getItem() == ModItems.gemAquamarine) return 1;
			else if(itemstack.getItem() == ModItems.gemCarnelian) return 1;
			else if(itemstack.getItem() == ModItems.gemCitrine) return 1;
			else if(itemstack.getItem() == Items.diamond) return 1;
			else if(itemstack.getItem() == Items.emerald) return 1;
			else if(itemstack.getItem() == ModItems.gemGarnet) return 1;
			else if(itemstack.getItem() == ModItems.gemJade) return 1;
			else if(itemstack.getItem() == ModItems.gemKunzite) return 1;
			else if(itemstack.getItem() == Items.quartz) return 1;
			else if(itemstack.getItem() == ModItems.gemOnyx) return 1;
			else if(itemstack.getItem() == ModItems.gemOpal) return 1;
			else if(itemstack.getItem() == ModItems.gemQuartz) return 1;
			else if(itemstack.getItem() == ModItems.gemRuby) return 1;
			else if(itemstack.getItem() == ModItems.gemSapphire) return 1;
			else if(itemstack.getItem() == ModItems.gemTopaz) return 1;
			else if(itemstack.getItem() == ModItems.fyrestone) return 1;
			else if(itemstack.getItem() == ModItems.voidium) return 1;
			else if(itemstack.getItem() == ModItems.iridium) return 1;
			else if(itemstack.getItem() == ModItems.plutonium) return 1;
			else if(itemstack.getItem() == ModItems.uranium) return 1;
			else if(itemstack.getItem() == Items.coal) return 1;
			else if(itemstack.getItem() == Items.dye && itemstack.getItemDamage() == 4) return 1;
			else if(itemstack.getItem() == ModItems.trytementium) return 1;
			else if(itemstack.getItem() == ModItems.unobtanium) return 1;
			
			else if(itemstack.getItem() == ModItems.clusterAdamanite) return 2;
			else if(itemstack.getItem() == ModItems.clusterAdamant) return 2;
			else if(itemstack.getItem() == ModItems.clusterAluminium) return 2;
			else if(itemstack.getItem() == ModItems.clusterBlurite) return 2;
			else if(itemstack.getItem() == ModItems.clusterBrass) return 2;
			else if(itemstack.getItem() == ModItems.clusterChromium) return 2;
			else if(itemstack.getItem() == ModItems.clusterCobalt) return 2;
			else if(itemstack.getItem() == ModItems.clusterCopper) return 2;
			else if(itemstack.getItem() == ModItems.clusterDaeyalt) return 2;
			else if(itemstack.getItem() == ModItems.clusterElectrum) return 2;
			else if(itemstack.getItem() == ModItems.clusterGold) return 2;
			else if(itemstack.getItem() == ModItems.clusterGoloid) return 2;
			else if(itemstack.getItem() == ModItems.clusterInvar) return 2;
			else if(itemstack.getItem() == ModItems.clusterIron) return 2;
			else if(itemstack.getItem() == ModItems.clusterLead) return 2;
			else if(itemstack.getItem() == ModItems.clusterLunar) return 2;
			else if(itemstack.getItem() == ModItems.clusterMalagnite) return 2;
			else if(itemstack.getItem() == ModItems.clusterManganese) return 2;
			else if(itemstack.getItem() == ModItems.clusterMithril) return 2;
			else if(itemstack.getItem() == ModItems.clusterNickel) return 2;
			else if(itemstack.getItem() == ModItems.clusterPlatinum) return 2;
			else if(itemstack.getItem() == ModItems.clusterRhodium) return 2;
			else if(itemstack.getItem() == ModItems.clusterRubium) return 2;
			else if(itemstack.getItem() == ModItems.clusterRunite) return 2;
			else if(itemstack.getItem() == ModItems.clusterSilicon) return 2;
			else if(itemstack.getItem() == ModItems.clusterSilver) return 2;
			else if(itemstack.getItem() == ModItems.clusterSolder) return 2;
			else if(itemstack.getItem() == ModItems.clusterSteel) return 2;
			else if(itemstack.getItem() == ModItems.clusterTin) return 2;
			else if(itemstack.getItem() == ModItems.clusterTitanium) return 2;
			else if(itemstack.getItem() == ModItems.clusterTungsten) return 2;
			else if(itemstack.getItem() == ModItems.clusterZinc) return 2;
			else if(itemstack.getItem() == ModItems.clusterAmazonite) return 2;
			else if(itemstack.getItem() == ModItems.clusterAmber) return 2;
			else if(itemstack.getItem() == ModItems.clusterAmethyst) return 2;
			else if(itemstack.getItem() == ModItems.clusterAquamarine) return 2;
			else if(itemstack.getItem() == ModItems.clusterCarnelian) return 2;
			else if(itemstack.getItem() == ModItems.clusterCitrine) return 2;
			else if(itemstack.getItem() == ModItems.clusterDiamond) return 2;
			else if(itemstack.getItem() == ModItems.clusterEmerald) return 2;
			else if(itemstack.getItem() == ModItems.clusterGarnet) return 2;
			else if(itemstack.getItem() == ModItems.clusterJade) return 2;
			else if(itemstack.getItem() == ModItems.clusterKunzite) return 2;
			else if(itemstack.getItem() == ModItems.clusterNetherQuartz) return 2;
			else if(itemstack.getItem() == ModItems.clusterOnyx) return 2;
			else if(itemstack.getItem() == ModItems.clusterOpal) return 2;
			else if(itemstack.getItem() == ModItems.clusterQuartz) return 2;
			else if(itemstack.getItem() == ModItems.clusterRuby) return 2;
			else if(itemstack.getItem() == ModItems.clusterSapphire) return 2;
			else if(itemstack.getItem() == ModItems.clusterTopaz) return 2;
			else if(itemstack.getItem() == ModItems.clusterFyrestone) return 2;
			else if(itemstack.getItem() == ModItems.clusterVoidium) return 2;
			else if(itemstack.getItem() == ModItems.clusterIridium) return 2;
			else if(itemstack.getItem() == ModItems.clusterPlutonium) return 2;
			else if(itemstack.getItem() == ModItems.clusterUranium) return 2;
			else if(itemstack.getItem() == ModItems.clusterCoal) return 2;
			else if(itemstack.getItem() == ModItems.clusterLapis) return 4;
			else if(itemstack.getItem() == ModItems.clusterRedstone) return 4;
			else if(itemstack.getItem() == ModItems.clusterTrytementium) return 2;
			else if(itemstack.getItem() == ModItems.clusterUnobtanium) return 2;
			
			else if(itemstack.getItem() == Items.bone) return 6;
			else if(itemstack.getItem() == ModItems.fossil && itemstack.getItemDamage() == 0) return 24;
			else if(itemstack.getItem() == ModItems.fossil && itemstack.getItemDamage() == 1) return 16;
			else if(itemstack.getItem() == ModItems.fossil && itemstack.getItemDamage() == 2) return 16;
			else if(itemstack.getItem() == ModItems.fossil && itemstack.getItemDamage() == 3) return 48;
			else if(itemstack.getItem() == ModItems.fossil && itemstack.getItemDamage() == 4) return 48;
			else if(itemstack.getItem() == ModItems.fossil && itemstack.getItemDamage() == 5) return 16;
			
			else if(itemstack.getItem() == Items.bread) return 1;
			else if(itemstack.getItem() == Items.wheat) return 2;
		} return 0;
	}
}
