// Date: 15/01/2015 3:41:30 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.omgimalexis.allthethings.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelShellArmour extends ModelBiped
{
  //fields
    ModelRenderer shell;
    ModelRenderer shell2;
  
  public ModelShellArmour()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      shell = new ModelRenderer(this, 0, 32);
      shell.addBox(-6F, 0F, 2F, 12, 16, 7);
      shell.setRotationPoint(0F, 0F, 0F);
      shell.setTextureSize(64, 64);
      shell.mirror = true;
      setRotation(shell, 0F, 0F, 0F);
      shell2 = new ModelRenderer(this, 38, 32);
      shell2.addBox(-5F, 1F, 9F, 10, 14, 2);
      shell2.setRotationPoint(0F, 0F, 0F);
      shell2.setTextureSize(64, 64);
      shell2.mirror = true;
      setRotation(shell2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    shell.render(f5);
    shell2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    this.shell.rotateAngleX = super.bipedBody.rotateAngleX;
    this.shell.rotateAngleY = super.bipedBody.rotateAngleY;
    this.shell.rotateAngleZ = super.bipedBody.rotateAngleZ;
    this.shell2.rotateAngleX = super.bipedBody.rotateAngleX;
    this.shell2.rotateAngleY = super.bipedBody.rotateAngleY;
    this.shell2.rotateAngleZ = super.bipedBody.rotateAngleZ;
  }

}
