// Date: 2/25/2015 1:56:47 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.omgimalexis.allthethings.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelSenthant extends ModelBase
{
  //fields
    ModelRenderer headMain;
    ModelRenderer headLeft;
    ModelRenderer headRight;
    ModelRenderer stemLeft;
    ModelRenderer stemRight;
    ModelRenderer body1;
    ModelRenderer body2;
    ModelRenderer body3;
    ModelRenderer tail;
    
    int j = 1;
  
  public ModelSenthant()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      headMain = new ModelRenderer(this, 0, 0);
      headMain.addBox(-4F, -10F, -4F, 8, 10, 8);
      headMain.setRotationPoint(0F, 0F, 0F);
      headMain.setTextureSize(64, 64);
      setRotation(headMain, 0F, 0F, 0F);
      headLeft = new ModelRenderer(this, 32, 0);
      headLeft.addBox(-3F, -6F, -3F, 6, 8, 6);
      headLeft.setRotationPoint(-7F, -13F, 0F);
      headLeft.setTextureSize(64, 64);
      setRotation(headLeft, 0F, 0F, 0F);
      headRight = new ModelRenderer(this, 32, 0);
      headRight.addBox(-3F, -6F, -3F, 6, 8, 6);
      headRight.setRotationPoint(7F, -13F, 0F);
      headRight.setTextureSize(64, 64);
      headRight.mirror = true;
      setRotation(headRight, 0F, 0F, 0F);
      stemLeft = new ModelRenderer(this, 32, 14);
      stemLeft.addBox(-4F, -0.5F, -0.5F, 4, 1, 3);
      stemLeft.setRotationPoint(-3F, -9F, -1F);
      stemLeft.setTextureSize(64, 64);
      setRotation(stemLeft, 0F, 0F, 0.7853982F);
      stemRight = new ModelRenderer(this, 32, 14);
      stemRight.addBox(0F, -0.5F, -0.5F, 4, 1, 3);
      stemRight.setRotationPoint(3F, -9F, -1F);
      stemRight.setTextureSize(64, 64);
      stemRight.mirror = true;
      setRotation(stemRight, 0F, 0F, -0.7853982F);
      body1 = new ModelRenderer(this, 0, 18);
      body1.addBox(-6F, 0F, 0F, 12, 12, 4);
      body1.setRotationPoint(0F, 0F, 0F);
      body1.setTextureSize(64, 64);
      setRotation(body1, 0F, 0F, 0F);
      body2 = new ModelRenderer(this, 32, 18);
      body2.addBox(-5F, 12F, 1F, 10, 5, 4);
      body2.setRotationPoint(0F, 0F, 0F);
      body2.setTextureSize(64, 64);
      setRotation(body2, 0F, 0F, 0F);
      body3 = new ModelRenderer(this, 32, 27);
      body3.addBox(-4F, 17F, 2F, 8, 4, 4);
      body3.setRotationPoint(0F, 0F, 0F);
      body3.setTextureSize(64, 64);
      setRotation(body3, 0F, 0F, 0F);
      tail = new ModelRenderer(this, 0, 34);
      tail.addBox(-3F, 21F, 3F, 6, 3, 6);
      tail.setRotationPoint(0F, 0F, 0F);
      tail.setTextureSize(64, 64);
      setRotation(tail, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    headMain.render(f5);
    headLeft.render(f5);
    headRight.render(f5);
    stemLeft.render(f5);
    stemRight.render(f5);
    body1.render(f5);
    body2.render(f5);
    body3.render(f5);
    tail.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    this.headMain.rotateAngleX = f4 / (180F / (float)Math.PI);
    this.headMain.rotateAngleY = f3 / (180F / (float)Math.PI);
    this.headLeft.rotateAngleX = f4 / (180F / (float)Math.PI);
    this.headLeft.rotateAngleY += 0.03;
    this.headRight.rotateAngleX = f4 / (180F / (float)Math.PI);
    this.headRight.rotateAngleY -= 0.03;
    if(this.body1.rotateAngleX >= 0.3F) {
    	j = -1;
    } else if(this.body1.rotateAngleX <= 0F) {
    	j = 1;
    }
    this.body1.rotateAngleX += (j*0.003F);
    this.body2.rotateAngleX += (j*0.003F);
    this.body3.rotateAngleX += (j*0.003F);
    this.tail.rotateAngleX += (j*0.003F);
  }

}
