package omgimalexis.allthethings.init;

import omgimalexis.allthethings.creativetabs.TMCreativeTabs;
import omgimalexis.allthethings.handler.BucketHandler;
import omgimalexis.allthethings.item.ItemBasicBucket;
import omgimalexis.allthethings.utility.Register;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fluids.FluidContainerRegistry;
import net.minecraftforge.fluids.FluidRegistry;
import net.minecraftforge.fluids.FluidStack;
import cpw.mods.fml.common.registry.GameRegistry;

public class ModBuckets {
	public static final ItemBasicBucket moltenIronBucket = new ItemBasicBucket(ModBlocks.moltenIron, "ironMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenGoldBucket = new ItemBasicBucket(ModBlocks.moltenGold, "goldMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenCopperBucket = new ItemBasicBucket(ModBlocks.moltenCopper, "copperMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenTinBucket = new ItemBasicBucket(ModBlocks.moltenTin, "tinMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenLeadBucket = new ItemBasicBucket(ModBlocks.moltenLead, "leadMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenSilverBucket = new ItemBasicBucket(ModBlocks.moltenSilver, "silverMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenBronzeBucket = new ItemBasicBucket(ModBlocks.moltenBronze, "bronzeMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenPlatinumBucket = new ItemBasicBucket(ModBlocks.moltenPlatinum, "platinumMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenZincBucket = new ItemBasicBucket(ModBlocks.moltenZinc, "zincMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenSolderBucket = new ItemBasicBucket(ModBlocks.moltenSolder, "solderMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenBrassBucket = new ItemBasicBucket(ModBlocks.moltenBrass, "brassMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenElectrumBucket = new ItemBasicBucket(ModBlocks.moltenElectrum, "electrumMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenMalagniteBucket = new ItemBasicBucket(ModBlocks.moltenMalagnite, "malagniteMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenAluminiumBucket = new ItemBasicBucket(ModBlocks.moltenAluminium, "aluminiumMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenGoloidBucket = new ItemBasicBucket(ModBlocks.moltenGoloid, "goloidMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenSiliconBucket = new ItemBasicBucket(ModBlocks.moltenSilicon, "siliconMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenVoidiumBucket = new ItemBasicBucket(ModBlocks.moltenVoidium, "voidiumMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenRhodiumBucket = new ItemBasicBucket(ModBlocks.moltenRhodium, "rhodiumMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenTungstenBucket = new ItemBasicBucket(ModBlocks.moltenTungsten, "tungstenMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenCobaltBucket = new ItemBasicBucket(ModBlocks.moltenCobalt, "cobaltMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenInvarBucket = new ItemBasicBucket(ModBlocks.moltenInvar, "invarMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenTrytementiumBucket = new ItemBasicBucket(ModBlocks.moltenTrytementium, "trytementiumMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenNickelBucket = new ItemBasicBucket(ModBlocks.moltenNickel, "nickelMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenChromiumBucket = new ItemBasicBucket(ModBlocks.moltenChromium, "chromiumMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenUnobtaniumBucket = new ItemBasicBucket(ModBlocks.moltenUnobtanium, "unobtaniumMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenPlutoniumBucket = new ItemBasicBucket(ModBlocks.moltenPlutonium, "plutoniumMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenUraniumBucket = new ItemBasicBucket(ModBlocks.moltenUranium, "uraniumMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenIridiumBucket = new ItemBasicBucket(ModBlocks.moltenIridium, "iridiumMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenBluriteBucket = new ItemBasicBucket(ModBlocks.moltenBlurite, "bluriteMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenRuniteBucket = new ItemBasicBucket(ModBlocks.moltenRunite, "runiteMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenRubiumBucket = new ItemBasicBucket(ModBlocks.moltenRubium, "rubiumMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenLunarBucket = new ItemBasicBucket(ModBlocks.moltenLunar, "lunarMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenOpalBucket = new ItemBasicBucket(ModBlocks.moltenOpal, "opalMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenDaeyaltBucket = new ItemBasicBucket(ModBlocks.moltenDaeyalt, "daeyaltMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenRubyBucket = new ItemBasicBucket(ModBlocks.moltenRuby, "rubyMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenSapphireBucket = new ItemBasicBucket(ModBlocks.moltenSapphire, "sapphireMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenEmeraldBucket = new ItemBasicBucket(ModBlocks.moltenEmerald, "emeraldMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenDiamondBucket = new ItemBasicBucket(ModBlocks.moltenDiamond, "diamondMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenNetherQuartzBucket = new ItemBasicBucket(ModBlocks.moltenNetherQuartz, "netherQuartzMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenObsidianBucket = new ItemBasicBucket(ModBlocks.moltenObsidian, "obsidianMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenOnyxBucket = new ItemBasicBucket(ModBlocks.moltenOnyx, "onyxMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenKunziteBucket = new ItemBasicBucket(ModBlocks.moltenKunzite, "kunziteMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenAmberBucket = new ItemBasicBucket(ModBlocks.moltenAmber, "amberMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenGarnetBucket = new ItemBasicBucket(ModBlocks.moltenGarnet, "garnetMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenAmazoniteBucket = new ItemBasicBucket(ModBlocks.moltenAmazonite, "amazoniteMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenFyrestoneBucket = new ItemBasicBucket(ModBlocks.moltenFyrestone, "fyrestoneMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenAquamarineBucket = new ItemBasicBucket(ModBlocks.moltenAquamarine, "aquamarineMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenTopazBucket = new ItemBasicBucket(ModBlocks.moltenTopaz, "topazMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenCarnelianBucket = new ItemBasicBucket(ModBlocks.moltenCarnelian, "carnelianMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenJadeBucket = new ItemBasicBucket(ModBlocks.moltenJade, "jadeMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenAmethystBucket = new ItemBasicBucket(ModBlocks.moltenAmethyst, "amethystMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenCitrineBucket = new ItemBasicBucket(ModBlocks.moltenCitrine, "citrineMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenMithrilBucket = new ItemBasicBucket(ModBlocks.moltenMithril, "mithrilMoltenBucket", TMCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenManganeseBucket = new ItemBasicBucket(ModBlocks.moltenManganese, "manganeseMoltenBucket", TMCreativeTabs.liquid, 1);
	
	public static void init() {
		Register.addBucket(moltenIronBucket, moltenIronBucket.getUnlocalizedName(), ModFluids.moltenIronFluid, ModBlocks.moltenIron);
		Register.addBucket(moltenGoldBucket, moltenGoldBucket.getUnlocalizedName(), ModFluids.moltenGoldFluid, ModBlocks.moltenGold);
		Register.addBucket(moltenCopperBucket, moltenCopperBucket.getUnlocalizedName(), ModFluids.moltenCopperFluid, ModBlocks.moltenCopper);
		Register.addBucket(moltenTinBucket, moltenTinBucket.getUnlocalizedName(), ModFluids.moltenTinFluid, ModBlocks.moltenTin);
		Register.addBucket(moltenLeadBucket, moltenLeadBucket.getUnlocalizedName(), ModFluids.moltenLeadFluid, ModBlocks.moltenLead);
		Register.addBucket(moltenSilverBucket, moltenSilverBucket.getUnlocalizedName(), ModFluids.moltenSilverFluid, ModBlocks.moltenSilver);
		Register.addBucket(moltenBronzeBucket, moltenBronzeBucket.getUnlocalizedName(), ModFluids.moltenBronzeFluid, ModBlocks.moltenBronze);
		Register.addBucket(moltenPlatinumBucket, moltenPlatinumBucket.getUnlocalizedName(), ModFluids.moltenPlatinumFluid, ModBlocks.moltenPlatinum);
		Register.addBucket(moltenZincBucket, moltenZincBucket.getUnlocalizedName(), ModFluids.moltenZincFluid, ModBlocks.moltenZinc);
		Register.addBucket(moltenSolderBucket, moltenSolderBucket.getUnlocalizedName(), ModFluids.moltenSolderFluid, ModBlocks.moltenSolder);
		Register.addBucket(moltenBrassBucket, moltenBrassBucket.getUnlocalizedName(), ModFluids.moltenBrassFluid, ModBlocks.moltenBrass);
		Register.addBucket(moltenElectrumBucket, moltenElectrumBucket.getUnlocalizedName(), ModFluids.moltenElectrumFluid, ModBlocks.moltenElectrum);
		Register.addBucket(moltenMalagniteBucket, moltenMalagniteBucket.getUnlocalizedName(), ModFluids.moltenMalagniteFluid, ModBlocks.moltenMalagnite);
		Register.addBucket(moltenAluminiumBucket, moltenAluminiumBucket.getUnlocalizedName(), ModFluids.moltenAluminiumFluid, ModBlocks.moltenAluminium);
		Register.addBucket(moltenGoloidBucket, moltenGoloidBucket.getUnlocalizedName(), ModFluids.moltenGoloidFluid, ModBlocks.moltenGoloid);
		Register.addBucket(moltenSiliconBucket, moltenSiliconBucket.getUnlocalizedName(), ModFluids.moltenSiliconFluid, ModBlocks.moltenSilicon);
		Register.addBucket(moltenVoidiumBucket, moltenVoidiumBucket.getUnlocalizedName(), ModFluids.moltenVoidiumFluid, ModBlocks.moltenVoidium);
		Register.addBucket(moltenRhodiumBucket, moltenRhodiumBucket.getUnlocalizedName(), ModFluids.moltenRhodiumFluid, ModBlocks.moltenRhodium);
		Register.addBucket(moltenTungstenBucket, moltenTungstenBucket.getUnlocalizedName(), ModFluids.moltenTungstenFluid, ModBlocks.moltenTungsten);
		Register.addBucket(moltenCobaltBucket, moltenCobaltBucket.getUnlocalizedName(), ModFluids.moltenCobaltFluid, ModBlocks.moltenCobalt);
		Register.addBucket(moltenInvarBucket, moltenInvarBucket.getUnlocalizedName(), ModFluids.moltenInvarFluid, ModBlocks.moltenInvar);
		Register.addBucket(moltenTrytementiumBucket, moltenTrytementiumBucket.getUnlocalizedName(), ModFluids.moltenTrytementiumFluid, ModBlocks.moltenTrytementium);
		Register.addBucket(moltenNickelBucket, moltenNickelBucket.getUnlocalizedName(), ModFluids.moltenNickelFluid, ModBlocks.moltenNickel);
		Register.addBucket(moltenChromiumBucket, moltenChromiumBucket.getUnlocalizedName(), ModFluids.moltenChromiumFluid, ModBlocks.moltenChromium);
		Register.addBucket(moltenUnobtaniumBucket, moltenUnobtaniumBucket.getUnlocalizedName(), ModFluids.moltenUnobtaniumFluid, ModBlocks.moltenUnobtanium);
		Register.addBucket(moltenPlutoniumBucket, moltenPlutoniumBucket.getUnlocalizedName(), ModFluids.moltenPlutoniumFluid, ModBlocks.moltenPlutonium);
		Register.addBucket(moltenUraniumBucket, moltenUraniumBucket.getUnlocalizedName(), ModFluids.moltenUraniumFluid, ModBlocks.moltenUranium);
		Register.addBucket(moltenIridiumBucket, moltenIridiumBucket.getUnlocalizedName(), ModFluids.moltenIridiumFluid, ModBlocks.moltenIridium);
		Register.addBucket(moltenBluriteBucket, moltenBluriteBucket.getUnlocalizedName(), ModFluids.moltenBluriteFluid, ModBlocks.moltenBlurite);
		Register.addBucket(moltenRuniteBucket, moltenRuniteBucket.getUnlocalizedName(), ModFluids.moltenRuniteFluid, ModBlocks.moltenRunite);
		Register.addBucket(moltenRubiumBucket, moltenRubiumBucket.getUnlocalizedName(), ModFluids.moltenRubiumFluid, ModBlocks.moltenRubium);
		Register.addBucket(moltenLunarBucket, moltenLunarBucket.getUnlocalizedName(), ModFluids.moltenLunarFluid, ModBlocks.moltenLunar);
		Register.addBucket(moltenOpalBucket, moltenOpalBucket.getUnlocalizedName(), ModFluids.moltenOpalFluid, ModBlocks.moltenOpal);
		Register.addBucket(moltenDaeyaltBucket, moltenDaeyaltBucket.getUnlocalizedName(), ModFluids.moltenDaeyaltFluid, ModBlocks.moltenDaeyalt);
		Register.addBucket(moltenRubyBucket, moltenRubyBucket.getUnlocalizedName(), ModFluids.moltenRubyFluid, ModBlocks.moltenRuby);
		Register.addBucket(moltenSapphireBucket, moltenSapphireBucket.getUnlocalizedName(), ModFluids.moltenSapphireFluid, ModBlocks.moltenSapphire);
		Register.addBucket(moltenEmeraldBucket, moltenEmeraldBucket.getUnlocalizedName(), ModFluids.moltenEmeraldFluid, ModBlocks.moltenEmerald);
		Register.addBucket(moltenDiamondBucket, moltenDiamondBucket.getUnlocalizedName(), ModFluids.moltenDiamondFluid, ModBlocks.moltenDiamond);
		Register.addBucket(moltenNetherQuartzBucket, moltenNetherQuartzBucket.getUnlocalizedName(), ModFluids.moltenNetherQuartzFluid, ModBlocks.moltenNetherQuartz);
		Register.addBucket(moltenObsidianBucket, moltenObsidianBucket.getUnlocalizedName(), ModFluids.moltenObsidianFluid, ModBlocks.moltenObsidian);
		Register.addBucket(moltenOnyxBucket, moltenOnyxBucket.getUnlocalizedName(), ModFluids.moltenOnyxFluid, ModBlocks.moltenOnyx);
		Register.addBucket(moltenKunziteBucket, moltenKunziteBucket.getUnlocalizedName(), ModFluids.moltenKunziteFluid, ModBlocks.moltenKunzite);
		Register.addBucket(moltenAmberBucket, moltenAmberBucket.getUnlocalizedName(), ModFluids.moltenAmberFluid, ModBlocks.moltenAmber);
		Register.addBucket(moltenGarnetBucket, moltenGarnetBucket.getUnlocalizedName(), ModFluids.moltenGarnetFluid, ModBlocks.moltenGarnet);
		Register.addBucket(moltenAmazoniteBucket, moltenAmazoniteBucket.getUnlocalizedName(), ModFluids.moltenAmazoniteFluid, ModBlocks.moltenAmazonite);
		Register.addBucket(moltenFyrestoneBucket, moltenFyrestoneBucket.getUnlocalizedName(), ModFluids.moltenFyrestoneFluid, ModBlocks.moltenFyrestone);
		Register.addBucket(moltenAquamarineBucket, moltenAquamarineBucket.getUnlocalizedName(), ModFluids.moltenAquamarineFluid, ModBlocks.moltenAquamarine);
		Register.addBucket(moltenTopazBucket, moltenTopazBucket.getUnlocalizedName(), ModFluids.moltenTopazFluid, ModBlocks.moltenTopaz);
		Register.addBucket(moltenCarnelianBucket, moltenCarnelianBucket.getUnlocalizedName(), ModFluids.moltenCarnelianFluid, ModBlocks.moltenCarnelian);
		Register.addBucket(moltenJadeBucket, moltenJadeBucket.getUnlocalizedName(), ModFluids.moltenJadeFluid, ModBlocks.moltenJade);
		Register.addBucket(moltenAmethystBucket, moltenAmethystBucket.getUnlocalizedName(), ModFluids.moltenAmethystFluid, ModBlocks.moltenAmethyst);
		Register.addBucket(moltenCitrineBucket, moltenCitrineBucket.getUnlocalizedName(), ModFluids.moltenCitrineFluid, ModBlocks.moltenCitrine);
		Register.addBucket(moltenMithrilBucket, moltenMithrilBucket.getUnlocalizedName(), ModFluids.moltenMithrilFluid, ModBlocks.moltenMithril);
		Register.addBucket(moltenManganeseBucket, moltenManganeseBucket.getUnlocalizedName(), ModFluids.moltenManganeseFluid, ModBlocks.moltenManganese);
	}
}
