// Date: 31/07/2015 5:17:26 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.shnupbups.allthethings.model;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelMouse extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer EarLeft;
    ModelRenderer Tail;
    ModelRenderer EarRight;
    ModelRenderer Nose;
  
  public ModelMouse()
  {
    textureWidth = 32;
    textureHeight = 32;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(-2F, -2F, -1F, 4, 4, 6);
      Body.setRotationPoint(0F, 22F, -1F);
      Body.setTextureSize(32, 32);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      EarLeft = new ModelRenderer(this, 12, 10);
      EarLeft.addBox(-1F, -3F, -1F, 3, 4, 2);
      EarLeft.setRotationPoint(2F, 20F, -0.5F);
      EarLeft.setTextureSize(32, 32);
      setRotation(EarLeft, 0F, 0F, 0F);
      Tail = new ModelRenderer(this, 0, 10);
      Tail.addBox(-1F, 0F, 0F, 2, 1, 8);
      Tail.setRotationPoint(0F, 23F, 2F);
      Tail.setTextureSize(32, 32);
      Tail.mirror = true;
      setRotation(Tail, 0F, 0F, 0F);
      EarRight = new ModelRenderer(this, 14, 0);
      EarRight.addBox(-2F, -3F, -1F, 3, 4, 2);
      EarRight.setRotationPoint(-2F, 20F, -0.5F);
      EarRight.setTextureSize(32, 32);
      EarRight.mirror = true;
      setRotation(EarRight, 0F, 0F, 0F);
      Nose = new ModelRenderer(this, 0, 10);
      Nose.addBox(-1F, -1F, -1F, 2, 2, 1);
      Nose.setRotationPoint(0F, 22.6F, -2F);
      Nose.setTextureSize(32, 32);
      Nose.mirror = true;
      setRotation(Nose, 0F, 0F, 0F);
  }
  
  public void render(Entity p_78088_1_, float p_78088_2_, float p_78088_3_, float p_78088_4_, float p_78088_5_, float p_78088_6_, float p_78088_7_)
  {
      super.render(p_78088_1_, p_78088_2_, p_78088_3_, p_78088_4_, p_78088_5_, p_78088_6_, p_78088_7_);
      this.setRotationAngles(p_78088_2_, p_78088_3_, p_78088_4_, p_78088_5_, p_78088_6_, p_78088_7_, p_78088_1_);

      if (this.isChild)
      {
          float f6 = 2.0F;
          GL11.glPushMatrix();
          GL11.glScalef((1.0F / 2.0F) / f6, (1.0F / 2.0F) / f6, (1.0F / 2.0F) / f6);
          GL11.glTranslatef(0.0F, 72.4F * p_78088_7_, -0.1F);
          this.Body.render(p_78088_7_);
          this.Nose.render(p_78088_7_);
          this.EarLeft.render(p_78088_7_);
          this.EarRight.render(p_78088_7_);
          this.Tail.renderWithRotation(p_78088_7_);
          GL11.glPopMatrix();
      }
      else
      {
      	  GL11.glPushMatrix();
          GL11.glScalef(1.0F / 2.0F, 1.0F / 2.0F, 1.0F / 2.0F);
          GL11.glTranslatef(0.0F, 24.0F * p_78088_7_, -0.15F);
          this.Body.render(p_78088_7_);
          this.Nose.render(p_78088_7_);
          this.EarLeft.render(p_78088_7_);
          this.EarRight.render(p_78088_7_);
          this.Tail.renderWithRotation(p_78088_7_);
          GL11.glPopMatrix();
      }
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
