// Date: 27/2/2015 03:12:41pm
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package com.shnupbups.allthethings.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelGrawquat extends ModelBase {
	// fields
	ModelRenderer head;
	ModelRenderer body;
	ModelRenderer leg1;
	ModelRenderer leg2;
	ModelRenderer leg3;
	ModelRenderer leg4;
	ModelRenderer horn1;
	ModelRenderer horn2;
	ModelRenderer tail;
	ModelRenderer body2;

	public ModelGrawquat() {
		textureWidth=64;
		textureHeight=64;
		head=new ModelRenderer(this,0,0);
		head.addBox(-4F,-4F,-6F,8,8,6);
		head.setRotationPoint(0F,4F,-8F);
		head.setTextureSize(64,64);
		head.mirror=true;
		setRotation(head,0F,0F,0F);
		body=new ModelRenderer(this,20,9);
		body.addBox(-6F,-10F,-7F,12,18,10);
		body.setRotationPoint(0F,5F,2F);
		body.setTextureSize(64,64);
		body.mirror=true;
		setRotation(body,1.570796F,0F,0F);
		leg1=new ModelRenderer(this,0,14);
		leg1.addBox(-3F,0F,-2F,4,12,4);
		leg1.setRotationPoint(-3F,12F,7F);
		leg1.setTextureSize(64,64);
		leg1.mirror=true;
		setRotation(leg1,0F,0F,0F);
		leg2=new ModelRenderer(this,0,14);
		leg2.addBox(-1F,0F,-2F,4,12,4);
		leg2.setRotationPoint(3F,12F,7F);
		leg2.setTextureSize(64,64);
		leg2.mirror=true;
		setRotation(leg2,0F,0F,0F);
		leg3=new ModelRenderer(this,0,14);
		leg3.addBox(-3F,0F,-3F,4,12,4);
		leg3.setRotationPoint(-3F,12F,-5F);
		leg3.setTextureSize(64,64);
		leg3.mirror=true;
		setRotation(leg3,0F,0F,0F);
		leg4=new ModelRenderer(this,0,14);
		leg4.addBox(-1F,0F,-3F,4,12,4);
		leg4.setRotationPoint(3F,12F,-5F);
		leg4.setTextureSize(64,64);
		leg4.mirror=true;
		setRotation(leg4,0F,0F,0F);
		horn1=new ModelRenderer(this,28,0);
		horn1.addBox(-2F,-11F,-4F,2,8,1);
		horn1.setRotationPoint(0F,4F,-8F);
		horn1.setTextureSize(64,64);
		horn1.mirror=true;
		setRotation(horn1,0F,0F,-0.7853982F);
		horn2=new ModelRenderer(this,28,0);
		horn2.addBox(0F,-11F,-4F,2,8,1);
		horn2.setRotationPoint(0F,4F,-8F);
		horn2.setTextureSize(64,64);
		horn2.mirror=true;
		setRotation(horn2,0F,0F,0.7853982F);
		tail=new ModelRenderer(this,16,14);
		tail.addBox(-0.5F,0F,0.5F,1,12,1);
		tail.setRotationPoint(0F,3F,9.5F);
		tail.setTextureSize(64,64);
		tail.mirror=true;
		setRotation(tail,0F,0F,0F);
		body2=new ModelRenderer(this,0,37);
		body2.addBox(-5F,-9F,3F,10,16,2);
		body2.setRotationPoint(0F,5F,2F);
		body2.setTextureSize(64,64);
		body2.mirror=true;
		setRotation(body2,1.570796F,0F,0F);
	}

	public void render(Entity entity,float f,float f1,float f2,float f3,float f4,float f5) {
		super.render(entity,f,f1,f2,f3,f4,f5);
		setRotationAngles(f,f1,f2,f3,f4,f5,entity);
		head.render(f5);
		body.render(f5);
		leg1.render(f5);
		leg2.render(f5);
		leg3.render(f5);
		leg4.render(f5);
		horn1.render(f5);
		horn2.render(f5);
		tail.render(f5);
		body2.render(f5);
	}

	private void setRotation(ModelRenderer model,float x,float y,float z) {
		model.rotateAngleX=x;
		model.rotateAngleY=y;
		model.rotateAngleZ=z;
	}

	public void setRotationAngles(float f,float f1,float f2,float f3,float f4,float f5,Entity entity) {
		super.setRotationAngles(f,f1,f2,f3,f4,f5,entity);
		float f6=(180F/(float)Math.PI);
		this.head.rotateAngleX=f4/(180F/(float)Math.PI);
		this.head.rotateAngleY=f3/(180F/(float)Math.PI);
		this.body.rotateAngleX=((float)Math.PI/2F);
		this.leg1.rotateAngleX=MathHelper.cos(f*0.6662F)*1.4F*f1;
		this.leg2.rotateAngleX=MathHelper.cos(f*0.6662F+(float)Math.PI)*1.4F*f1;
		this.leg3.rotateAngleX=MathHelper.cos(f*0.6662F+(float)Math.PI)*1.4F*f1;
		this.leg4.rotateAngleX=MathHelper.cos(f*0.6662F)*1.4F*f1;
		body2.rotateAngleX=body.rotateAngleX;
		body2.rotateAngleY=body.rotateAngleY;
		body2.rotateAngleZ=body.rotateAngleZ;
		horn1.rotateAngleX=head.rotateAngleX;
		horn1.rotateAngleY=head.rotateAngleY;
		horn1.rotateAngleZ=head.rotateAngleZ-0.3F;
		horn2.rotateAngleX=head.rotateAngleX;
		horn2.rotateAngleY=head.rotateAngleY;
		horn2.rotateAngleZ=head.rotateAngleZ+0.3F;
		tail.rotateAngleZ=MathHelper.cos(f*0.6662F)*1.4F*f1;
	}
}
