package com.shnupbups.allthethings.init;

import com.shnupbups.allthethings.handler.BucketHandler;
import com.shnupbups.allthethings.item.ItemBasicBucket;
import com.shnupbups.allthethings.utility.Register;

import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fluids.FluidContainerRegistry;
import net.minecraftforge.fluids.FluidRegistry;
import net.minecraftforge.fluids.FluidStack;
import cpw.mods.fml.common.registry.GameRegistry;

public class ModBuckets {
	public static final ItemBasicBucket moltenIronBucket = new ItemBasicBucket(ModBlocks.moltenIron, "ironMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenGoldBucket = new ItemBasicBucket(ModBlocks.moltenGold, "goldMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenCopperBucket = new ItemBasicBucket(ModBlocks.moltenCopper, "copperMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenTinBucket = new ItemBasicBucket(ModBlocks.moltenTin, "tinMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenLeadBucket = new ItemBasicBucket(ModBlocks.moltenLead, "leadMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenSilverBucket = new ItemBasicBucket(ModBlocks.moltenSilver, "silverMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenBronzeBucket = new ItemBasicBucket(ModBlocks.moltenBronze, "bronzeMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenPlatinumBucket = new ItemBasicBucket(ModBlocks.moltenPlatinum, "platinumMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenZincBucket = new ItemBasicBucket(ModBlocks.moltenZinc, "zincMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenSolderBucket = new ItemBasicBucket(ModBlocks.moltenSolder, "solderMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenBrassBucket = new ItemBasicBucket(ModBlocks.moltenBrass, "brassMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenSteelBucket = new ItemBasicBucket(ModBlocks.moltenSteel, "steelMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenElectrumBucket = new ItemBasicBucket(ModBlocks.moltenElectrum, "electrumMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenMalagniteBucket = new ItemBasicBucket(ModBlocks.moltenMalagnite, "malagniteMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenAluminiumBucket = new ItemBasicBucket(ModBlocks.moltenAluminium, "aluminiumMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenGoloidBucket = new ItemBasicBucket(ModBlocks.moltenGoloid, "goloidMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenSiliconBucket = new ItemBasicBucket(ModBlocks.moltenSilicon, "siliconMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenVoidiumBucket = new ItemBasicBucket(ModBlocks.moltenVoidium, "voidiumMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenRhodiumBucket = new ItemBasicBucket(ModBlocks.moltenRhodium, "rhodiumMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenTungstenBucket = new ItemBasicBucket(ModBlocks.moltenTungsten, "tungstenMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenCobaltBucket = new ItemBasicBucket(ModBlocks.moltenCobalt, "cobaltMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenInvarBucket = new ItemBasicBucket(ModBlocks.moltenInvar, "invarMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenTrytementiumBucket = new ItemBasicBucket(ModBlocks.moltenTrytementium, "trytementiumMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenNickelBucket = new ItemBasicBucket(ModBlocks.moltenNickel, "nickelMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenChromiumBucket = new ItemBasicBucket(ModBlocks.moltenChromium, "chromiumMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenUnobtaniumBucket = new ItemBasicBucket(ModBlocks.moltenUnobtanium, "unobtaniumMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenPlutoniumBucket = new ItemBasicBucket(ModBlocks.moltenPlutonium, "plutoniumMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenUraniumBucket = new ItemBasicBucket(ModBlocks.moltenUranium, "uraniumMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenIridiumBucket = new ItemBasicBucket(ModBlocks.moltenIridium, "iridiumMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenBluriteBucket = new ItemBasicBucket(ModBlocks.moltenBlurite, "bluriteMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenRuniteBucket = new ItemBasicBucket(ModBlocks.moltenRunite, "runiteMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenRubiumBucket = new ItemBasicBucket(ModBlocks.moltenRubium, "rubiumMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenLunarBucket = new ItemBasicBucket(ModBlocks.moltenLunar, "lunarMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenOpalBucket = new ItemBasicBucket(ModBlocks.moltenOpal, "opalMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenDaeyaltBucket = new ItemBasicBucket(ModBlocks.moltenDaeyalt, "daeyaltMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenRubyBucket = new ItemBasicBucket(ModBlocks.moltenRuby, "rubyMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenSapphireBucket = new ItemBasicBucket(ModBlocks.moltenSapphire, "sapphireMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenEmeraldBucket = new ItemBasicBucket(ModBlocks.moltenEmerald, "emeraldMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenDiamondBucket = new ItemBasicBucket(ModBlocks.moltenDiamond, "diamondMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenNetherQuartzBucket = new ItemBasicBucket(ModBlocks.moltenNetherQuartz, "netherQuartzMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenObsidianBucket = new ItemBasicBucket(ModBlocks.moltenObsidian, "obsidianMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenOnyxBucket = new ItemBasicBucket(ModBlocks.moltenOnyx, "onyxMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenKunziteBucket = new ItemBasicBucket(ModBlocks.moltenKunzite, "kunziteMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenAmberBucket = new ItemBasicBucket(ModBlocks.moltenAmber, "amberMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenGarnetBucket = new ItemBasicBucket(ModBlocks.moltenGarnet, "garnetMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenAmazoniteBucket = new ItemBasicBucket(ModBlocks.moltenAmazonite, "amazoniteMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenFyrestoneBucket = new ItemBasicBucket(ModBlocks.moltenFyrestone, "fyrestoneMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenAquamarineBucket = new ItemBasicBucket(ModBlocks.moltenAquamarine, "aquamarineMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenTopazBucket = new ItemBasicBucket(ModBlocks.moltenTopaz, "topazMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenCarnelianBucket = new ItemBasicBucket(ModBlocks.moltenCarnelian, "carnelianMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenJadeBucket = new ItemBasicBucket(ModBlocks.moltenJade, "jadeMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenAmethystBucket = new ItemBasicBucket(ModBlocks.moltenAmethyst, "amethystMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenCitrineBucket = new ItemBasicBucket(ModBlocks.moltenCitrine, "citrineMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenMithrilBucket = new ItemBasicBucket(ModBlocks.moltenMithril, "mithrilMoltenBucket", ModCreativeTabs.liquid, 1);
	public static final ItemBasicBucket moltenManganeseBucket = new ItemBasicBucket(ModBlocks.moltenManganese, "manganeseMoltenBucket", ModCreativeTabs.liquid, 1);
	
	public static void init() {
		Register.registerBucket(moltenIronBucket, moltenIronBucket.getUnlocalizedName(), ModFluids.moltenIronFluid, ModBlocks.moltenIron);
		Register.registerBucket(moltenGoldBucket, moltenGoldBucket.getUnlocalizedName(), ModFluids.moltenGoldFluid, ModBlocks.moltenGold);
		Register.registerBucket(moltenCopperBucket, moltenCopperBucket.getUnlocalizedName(), ModFluids.moltenCopperFluid, ModBlocks.moltenCopper);
		Register.registerBucket(moltenTinBucket, moltenTinBucket.getUnlocalizedName(), ModFluids.moltenTinFluid, ModBlocks.moltenTin);
		Register.registerBucket(moltenLeadBucket, moltenLeadBucket.getUnlocalizedName(), ModFluids.moltenLeadFluid, ModBlocks.moltenLead);
		Register.registerBucket(moltenSilverBucket, moltenSilverBucket.getUnlocalizedName(), ModFluids.moltenSilverFluid, ModBlocks.moltenSilver);
		Register.registerBucket(moltenBronzeBucket, moltenBronzeBucket.getUnlocalizedName(), ModFluids.moltenBronzeFluid, ModBlocks.moltenBronze);
		Register.registerBucket(moltenPlatinumBucket, moltenPlatinumBucket.getUnlocalizedName(), ModFluids.moltenPlatinumFluid, ModBlocks.moltenPlatinum);
		Register.registerBucket(moltenZincBucket, moltenZincBucket.getUnlocalizedName(), ModFluids.moltenZincFluid, ModBlocks.moltenZinc);
		Register.registerBucket(moltenSolderBucket, moltenSolderBucket.getUnlocalizedName(), ModFluids.moltenSolderFluid, ModBlocks.moltenSolder);
		Register.registerBucket(moltenBrassBucket, moltenBrassBucket.getUnlocalizedName(), ModFluids.moltenBrassFluid, ModBlocks.moltenBrass);
		Register.registerBucket(moltenSteelBucket, moltenSteelBucket.getUnlocalizedName(), ModFluids.moltenSteelFluid, ModBlocks.moltenSteel);
		Register.registerBucket(moltenElectrumBucket, moltenElectrumBucket.getUnlocalizedName(), ModFluids.moltenElectrumFluid, ModBlocks.moltenElectrum);
		Register.registerBucket(moltenMalagniteBucket, moltenMalagniteBucket.getUnlocalizedName(), ModFluids.moltenMalagniteFluid, ModBlocks.moltenMalagnite);
		Register.registerBucket(moltenAluminiumBucket, moltenAluminiumBucket.getUnlocalizedName(), ModFluids.moltenAluminiumFluid, ModBlocks.moltenAluminium);
		Register.registerBucket(moltenGoloidBucket, moltenGoloidBucket.getUnlocalizedName(), ModFluids.moltenGoloidFluid, ModBlocks.moltenGoloid);
		Register.registerBucket(moltenSiliconBucket, moltenSiliconBucket.getUnlocalizedName(), ModFluids.moltenSiliconFluid, ModBlocks.moltenSilicon);
		Register.registerBucket(moltenVoidiumBucket, moltenVoidiumBucket.getUnlocalizedName(), ModFluids.moltenVoidiumFluid, ModBlocks.moltenVoidium);
		Register.registerBucket(moltenRhodiumBucket, moltenRhodiumBucket.getUnlocalizedName(), ModFluids.moltenRhodiumFluid, ModBlocks.moltenRhodium);
		Register.registerBucket(moltenTungstenBucket, moltenTungstenBucket.getUnlocalizedName(), ModFluids.moltenTungstenFluid, ModBlocks.moltenTungsten);
		Register.registerBucket(moltenCobaltBucket, moltenCobaltBucket.getUnlocalizedName(), ModFluids.moltenCobaltFluid, ModBlocks.moltenCobalt);
		Register.registerBucket(moltenInvarBucket, moltenInvarBucket.getUnlocalizedName(), ModFluids.moltenInvarFluid, ModBlocks.moltenInvar);
		Register.registerBucket(moltenTrytementiumBucket, moltenTrytementiumBucket.getUnlocalizedName(), ModFluids.moltenTrytementiumFluid, ModBlocks.moltenTrytementium);
		Register.registerBucket(moltenNickelBucket, moltenNickelBucket.getUnlocalizedName(), ModFluids.moltenNickelFluid, ModBlocks.moltenNickel);
		Register.registerBucket(moltenChromiumBucket, moltenChromiumBucket.getUnlocalizedName(), ModFluids.moltenChromiumFluid, ModBlocks.moltenChromium);
		Register.registerBucket(moltenUnobtaniumBucket, moltenUnobtaniumBucket.getUnlocalizedName(), ModFluids.moltenUnobtaniumFluid, ModBlocks.moltenUnobtanium);
		Register.registerBucket(moltenPlutoniumBucket, moltenPlutoniumBucket.getUnlocalizedName(), ModFluids.moltenPlutoniumFluid, ModBlocks.moltenPlutonium);
		Register.registerBucket(moltenUraniumBucket, moltenUraniumBucket.getUnlocalizedName(), ModFluids.moltenUraniumFluid, ModBlocks.moltenUranium);
		Register.registerBucket(moltenIridiumBucket, moltenIridiumBucket.getUnlocalizedName(), ModFluids.moltenIridiumFluid, ModBlocks.moltenIridium);
		Register.registerBucket(moltenBluriteBucket, moltenBluriteBucket.getUnlocalizedName(), ModFluids.moltenBluriteFluid, ModBlocks.moltenBlurite);
		Register.registerBucket(moltenRuniteBucket, moltenRuniteBucket.getUnlocalizedName(), ModFluids.moltenRuniteFluid, ModBlocks.moltenRunite);
		Register.registerBucket(moltenRubiumBucket, moltenRubiumBucket.getUnlocalizedName(), ModFluids.moltenRubiumFluid, ModBlocks.moltenRubium);
		Register.registerBucket(moltenLunarBucket, moltenLunarBucket.getUnlocalizedName(), ModFluids.moltenLunarFluid, ModBlocks.moltenLunar);
		Register.registerBucket(moltenOpalBucket, moltenOpalBucket.getUnlocalizedName(), ModFluids.moltenOpalFluid, ModBlocks.moltenOpal);
		Register.registerBucket(moltenDaeyaltBucket, moltenDaeyaltBucket.getUnlocalizedName(), ModFluids.moltenDaeyaltFluid, ModBlocks.moltenDaeyalt);
		Register.registerBucket(moltenRubyBucket, moltenRubyBucket.getUnlocalizedName(), ModFluids.moltenRubyFluid, ModBlocks.moltenRuby);
		Register.registerBucket(moltenSapphireBucket, moltenSapphireBucket.getUnlocalizedName(), ModFluids.moltenSapphireFluid, ModBlocks.moltenSapphire);
		Register.registerBucket(moltenEmeraldBucket, moltenEmeraldBucket.getUnlocalizedName(), ModFluids.moltenEmeraldFluid, ModBlocks.moltenEmerald);
		Register.registerBucket(moltenDiamondBucket, moltenDiamondBucket.getUnlocalizedName(), ModFluids.moltenDiamondFluid, ModBlocks.moltenDiamond);
		Register.registerBucket(moltenNetherQuartzBucket, moltenNetherQuartzBucket.getUnlocalizedName(), ModFluids.moltenNetherQuartzFluid, ModBlocks.moltenNetherQuartz);
		Register.registerBucket(moltenObsidianBucket, moltenObsidianBucket.getUnlocalizedName(), ModFluids.moltenObsidianFluid, ModBlocks.moltenObsidian);
		Register.registerBucket(moltenOnyxBucket, moltenOnyxBucket.getUnlocalizedName(), ModFluids.moltenOnyxFluid, ModBlocks.moltenOnyx);
		Register.registerBucket(moltenKunziteBucket, moltenKunziteBucket.getUnlocalizedName(), ModFluids.moltenKunziteFluid, ModBlocks.moltenKunzite);
		Register.registerBucket(moltenAmberBucket, moltenAmberBucket.getUnlocalizedName(), ModFluids.moltenAmberFluid, ModBlocks.moltenAmber);
		Register.registerBucket(moltenGarnetBucket, moltenGarnetBucket.getUnlocalizedName(), ModFluids.moltenGarnetFluid, ModBlocks.moltenGarnet);
		Register.registerBucket(moltenAmazoniteBucket, moltenAmazoniteBucket.getUnlocalizedName(), ModFluids.moltenAmazoniteFluid, ModBlocks.moltenAmazonite);
		Register.registerBucket(moltenFyrestoneBucket, moltenFyrestoneBucket.getUnlocalizedName(), ModFluids.moltenFyrestoneFluid, ModBlocks.moltenFyrestone);
		Register.registerBucket(moltenAquamarineBucket, moltenAquamarineBucket.getUnlocalizedName(), ModFluids.moltenAquamarineFluid, ModBlocks.moltenAquamarine);
		Register.registerBucket(moltenTopazBucket, moltenTopazBucket.getUnlocalizedName(), ModFluids.moltenTopazFluid, ModBlocks.moltenTopaz);
		Register.registerBucket(moltenCarnelianBucket, moltenCarnelianBucket.getUnlocalizedName(), ModFluids.moltenCarnelianFluid, ModBlocks.moltenCarnelian);
		Register.registerBucket(moltenJadeBucket, moltenJadeBucket.getUnlocalizedName(), ModFluids.moltenJadeFluid, ModBlocks.moltenJade);
		Register.registerBucket(moltenAmethystBucket, moltenAmethystBucket.getUnlocalizedName(), ModFluids.moltenAmethystFluid, ModBlocks.moltenAmethyst);
		Register.registerBucket(moltenCitrineBucket, moltenCitrineBucket.getUnlocalizedName(), ModFluids.moltenCitrineFluid, ModBlocks.moltenCitrine);
		Register.registerBucket(moltenMithrilBucket, moltenMithrilBucket.getUnlocalizedName(), ModFluids.moltenMithrilFluid, ModBlocks.moltenMithril);
		Register.registerBucket(moltenManganeseBucket, moltenManganeseBucket.getUnlocalizedName(), ModFluids.moltenManganeseFluid, ModBlocks.moltenManganese);
	}
}
