package com.shnupbups.allthethings.init;

import net.minecraftforge.fluids.Fluid;
import net.minecraftforge.fluids.FluidRegistry;
import com.shnupbups.allthethings.block.FluidBasic;
import com.shnupbups.allthethings.utility.LogHelper;

public class ModFluids {
	// .setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenAdamaniteFluid=new FluidBasic("moltenAdamaniteFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenAdamantFluid=new FluidBasic("moltenAdamantFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenAluminiumFluid=new FluidBasic("moltenAluminiumFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenBluriteFluid=new FluidBasic("moltenBluriteFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenBrassFluid=new FluidBasic("moltenBrassFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenBronzeFluid=new FluidBasic("moltenBronzeFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenChromiumFluid=new FluidBasic("moltenChromiumFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenCobaltFluid=new FluidBasic("moltenCobaltFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenCopperFluid=new FluidBasic("moltenCopperFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenDaeyaltFluid=new FluidBasic("moltenDaeyaltFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenElectrumFluid=new FluidBasic("moltenElectrumFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenGoldFluid=new FluidBasic("moltenGoldFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenGoloidFluid=new FluidBasic("moltenGoloidFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenInvarFluid=new FluidBasic("moltenInvarFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenIronFluid=new FluidBasic("moltenIronFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenLeadFluid=new FluidBasic("moltenLeadFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenLunarFluid=new FluidBasic("moltenLunarFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenMalagniteFluid=new FluidBasic("moltenMalagniteFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenManganeseFluid=new FluidBasic("moltenManganeseFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenMithrilFluid=new FluidBasic("moltenMithrilFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenNickelFluid=new FluidBasic("moltenNickelFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenPlatinumFluid=new FluidBasic("moltenPlatinumFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenRhodiumFluid=new FluidBasic("moltenRhodiumFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenRubiumFluid=new FluidBasic("moltenRubiumFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenRuniteFluid=new FluidBasic("moltenRuniteFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenSiliconFluid=new FluidBasic("moltenSiliconFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenSilverFluid=new FluidBasic("moltenSilverFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenSolderFluid=new FluidBasic("moltenSolderFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenSteelFluid=new FluidBasic("moltenSteelFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenTinFluid=new FluidBasic("moltenTinFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenTitaniumFluid=new FluidBasic("moltenTitaniumFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenTungstenFluid=new FluidBasic("moltenTungstenFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenZincFluid=new FluidBasic("moltenZincFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenAmazoniteFluid=new FluidBasic("moltenAmazoniteFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenAmberFluid=new FluidBasic("moltenAmberFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenAmethystFluid=new FluidBasic("moltenAmethystFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenAquamarineFluid=new FluidBasic("moltenAquamarineFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenCarnelianFluid=new FluidBasic("moltenCarnelianFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenCitrineFluid=new FluidBasic("moltenCitrineFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenDiamondFluid=new FluidBasic("moltenDiamondFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenEmeraldFluid=new FluidBasic("moltenEmeraldFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenGarnetFluid=new FluidBasic("moltenGarnetFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenJadeFluid=new FluidBasic("moltenJadeFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenKunziteFluid=new FluidBasic("moltenKunziteFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenNetherQuartzFluid=new FluidBasic("moltenNetherQuartzFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenOnyxFluid=new FluidBasic("moltenOnyxFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenOpalFluid=new FluidBasic("moltenOpalFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenQuartzFluid=new FluidBasic("moltenQuartzFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenRubyFluid=new FluidBasic("moltenRubyFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenSapphireFluid=new FluidBasic("moltenSapphireFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenTopazFluid=new FluidBasic("moltenTopazFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenVoidiumFluid=new FluidBasic("moltenVoidiumFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenFyrestoneFluid=new FluidBasic("moltenFyrestoneFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenIridiumFluid=new FluidBasic("moltenIridiumFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenPlutoniumFluid=new FluidBasic("moltenPlutoniumFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenUraniumFluid=new FluidBasic("moltenUraniumFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenCrymeretyeFluid=new FluidBasic("moltenCrymeretyeFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenGraeconthylyniumFluid=new FluidBasic("moltenGraeconthylyniumFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenMuktaphlyteFluid=new FluidBasic("moltenMuktaphlyteFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenJonjronyphyllFluid=new FluidBasic("moltenJonjronyphyllFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenKraktachnarFluid=new FluidBasic("moltenKraktachnarFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenSchulbradethenairdiviteFluid=new FluidBasic("moltenSchulbradethenairdiviteFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenXaldriodythidyteFluid=new FluidBasic("moltenXaldriodythidyteFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenTrytementiumFluid=new FluidBasic("moltenTrytementiumFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenUnobtaniumFluid=new FluidBasic("moltenUnobtaniumFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenCoalFluid=new FluidBasic("moltenCoalFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenLapisFluid=new FluidBasic("moltenLapisFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenObsidianFluid=new FluidBasic("moltenObsidianFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);
	public static Fluid moltenRedstoneFluid=new FluidBasic("moltenRedstoneFluid").setTemperature(1300).setViscosity(6000).setDensity(3000).setLuminosity(12);

	public static void init() {
		FluidRegistry.registerFluid(moltenAdamaniteFluid);
		FluidRegistry.registerFluid(moltenAdamantFluid);
		FluidRegistry.registerFluid(moltenAluminiumFluid);
		FluidRegistry.registerFluid(moltenBluriteFluid);
		FluidRegistry.registerFluid(moltenBrassFluid);
		FluidRegistry.registerFluid(moltenBronzeFluid);
		FluidRegistry.registerFluid(moltenChromiumFluid);
		FluidRegistry.registerFluid(moltenCobaltFluid);
		FluidRegistry.registerFluid(moltenCopperFluid);
		FluidRegistry.registerFluid(moltenDaeyaltFluid);
		FluidRegistry.registerFluid(moltenElectrumFluid);
		FluidRegistry.registerFluid(moltenGoldFluid);
		FluidRegistry.registerFluid(moltenGoloidFluid);
		FluidRegistry.registerFluid(moltenInvarFluid);
		FluidRegistry.registerFluid(moltenIronFluid);
		FluidRegistry.registerFluid(moltenLeadFluid);
		FluidRegistry.registerFluid(moltenLunarFluid);
		FluidRegistry.registerFluid(moltenMalagniteFluid);
		FluidRegistry.registerFluid(moltenManganeseFluid);
		FluidRegistry.registerFluid(moltenMithrilFluid);
		FluidRegistry.registerFluid(moltenNickelFluid);
		FluidRegistry.registerFluid(moltenPlatinumFluid);
		FluidRegistry.registerFluid(moltenRhodiumFluid);
		FluidRegistry.registerFluid(moltenRubiumFluid);
		FluidRegistry.registerFluid(moltenRuniteFluid);
		FluidRegistry.registerFluid(moltenSiliconFluid);
		FluidRegistry.registerFluid(moltenSilverFluid);
		FluidRegistry.registerFluid(moltenSolderFluid);
		FluidRegistry.registerFluid(moltenSteelFluid);
		FluidRegistry.registerFluid(moltenTinFluid);
		FluidRegistry.registerFluid(moltenTitaniumFluid);
		FluidRegistry.registerFluid(moltenTungstenFluid);
		FluidRegistry.registerFluid(moltenZincFluid);
		FluidRegistry.registerFluid(moltenAmazoniteFluid);
		FluidRegistry.registerFluid(moltenAmberFluid);
		FluidRegistry.registerFluid(moltenAmethystFluid);
		FluidRegistry.registerFluid(moltenAquamarineFluid);
		FluidRegistry.registerFluid(moltenCarnelianFluid);
		FluidRegistry.registerFluid(moltenCitrineFluid);
		FluidRegistry.registerFluid(moltenDiamondFluid);
		FluidRegistry.registerFluid(moltenEmeraldFluid);
		FluidRegistry.registerFluid(moltenGarnetFluid);
		FluidRegistry.registerFluid(moltenJadeFluid);
		FluidRegistry.registerFluid(moltenKunziteFluid);
		FluidRegistry.registerFluid(moltenNetherQuartzFluid);
		FluidRegistry.registerFluid(moltenOnyxFluid);
		FluidRegistry.registerFluid(moltenOpalFluid);
		FluidRegistry.registerFluid(moltenQuartzFluid);
		FluidRegistry.registerFluid(moltenRubyFluid);
		FluidRegistry.registerFluid(moltenSapphireFluid);
		FluidRegistry.registerFluid(moltenTopazFluid);
		FluidRegistry.registerFluid(moltenFyrestoneFluid);
		FluidRegistry.registerFluid(moltenVoidiumFluid);
		FluidRegistry.registerFluid(moltenIridiumFluid);
		FluidRegistry.registerFluid(moltenPlutoniumFluid);
		FluidRegistry.registerFluid(moltenUraniumFluid);
		FluidRegistry.registerFluid(moltenCrymeretyeFluid);
		FluidRegistry.registerFluid(moltenGraeconthylyniumFluid);
		FluidRegistry.registerFluid(moltenMuktaphlyteFluid);
		FluidRegistry.registerFluid(moltenJonjronyphyllFluid);
		FluidRegistry.registerFluid(moltenKraktachnarFluid);
		FluidRegistry.registerFluid(moltenSchulbradethenairdiviteFluid);
		FluidRegistry.registerFluid(moltenXaldriodythidyteFluid);
		FluidRegistry.registerFluid(moltenUnobtaniumFluid);
		FluidRegistry.registerFluid(moltenTrytementiumFluid);
		FluidRegistry.registerFluid(moltenCoalFluid);
		FluidRegistry.registerFluid(moltenLapisFluid);
		FluidRegistry.registerFluid(moltenObsidianFluid);
		FluidRegistry.registerFluid(moltenRedstoneFluid);
		LogHelper.info("Fluids initialized successfully!");
	}
}
